### PR TITLE
Serialize empty tuple into '[]'  instead of null

### LINKED ISSUE #4530: Empty `std::tuple<>` cannot be serialized and de-serialized
### Description

The behavior of serializing and de-sereailzing an empty tuple changed from `3.9.1` to `3.10.0`.

`null` used to de-serialize without a problem to `std::tuple<>` but since throws an error since `3.10.0`.

The change of behavior happened in https://github.com/nlohmann/json/pull/2576.

Note that I'm not entirely sure this is a bug per-say, but we relied on this behavior in https://github.com/luxonis/depthai-core so I decided to report in case the previous behavior was "more correct".

### Reproduction steps

To reproduce run the MRE with both `3.10.0` and `3.9.1`.

### Expected vs. actual results

Expected - `null` succesfully de-serializes when `j.get<std::tuple<>>()` is called on `null`.
Actual:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be array, but is null
```

### Minimal code example

```Shell
#include <nlohmann/json.hpp>

int main() {
    auto sourceTuple = std::tuple<>();
    nlohmann::json j = sourceTuple;
    auto returnedTuple = j.get<std::tuple<>>();
    return 0;
}
```

### Error messages

```Shell
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.302] type must be array, but is null
Aborted (core dumped)
```

### Compiler and operating system

Ubuntu 20.04, GCC 9.4.0

### Library version

3.11.3

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by codenut**
This PR fixes https://github.com/nlohmann/json/issues/4530 by serializing an empty tuple into `[]` instead of `null`.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

File: include/nlohmann/detail/conversions/to_json.hpp [hunk 1]
```diff
@@ -423,7 +423,8 @@ inline void to_json(BasicJsonType& j, const T& b)
 template<typename BasicJsonType, typename Tuple, std::size_t... Idx>
 inline void to_json_tuple_impl(BasicJsonType& j, const Tuple& t, index_sequence<Idx...> /*unused*/)
 {
-    j = { std::get<Idx>(t)... };
+    using array_t = typename BasicJsonType::array_t;
+    j = (sizeof...(Idx) == 0) ? array_t() : array_t{ std::get<Idx>(t)... };
```
Comment (gregmarr) [inline include/nlohmann/detail/conversions/to_json.hpp]: Could (should?) this be done as an overload instead?

Untested:
```
template<typename BasicJsonType, typename Tuple>
inline void to_json_tuple_impl(BasicJsonType& j, const Tuple& t, index_sequence<> /*unused*/)
{
    j = array_t();
}
```
or
```
template<typename BasicJsonType>
inline void to_json(BasicJsonType& j, const tuple<>& t)
{
    j = array_t();
}
```

**Comment by gregmarr** [comment]
Title has typo on empty

File: include/nlohmann/detail/conversions/to_json.hpp (hunk 1 above)
Comment (codenut) [reply include/nlohmann/detail/conversions/to_json.hpp]: That is much better than the ternary operator. Thanks!

**Comment by nlohmann** [comment]
The coverage job is now fixed in the `develop` branch. Please update.

File: include/nlohmann/detail/conversions/from_json.hpp [hunk 2]
```diff
@@ -448,6 +448,12 @@ std::tuple<Args...> from_json_tuple_impl_base(BasicJsonType&& j, index_sequence<
     return std::make_tuple(std::forward<BasicJsonType>(j).at(Idx).template get<Args>()...);
 }
 
+template<typename BasicJsonType>
+std::tuple<> from_json_tuple_impl_base(BasicJsonType& /*unused*/, index_sequence<> /*unused*/)
+{
+    return {};
```
Comment (nlohmann) [inline include/nlohmann/detail/conversions/from_json.hpp:454]:
```suggestion
    return array_t();
```

Braced initialization is somewhat cursed in this library (see https://json.nlohmann.me/home/faq/#brace-initialization-yields-arrays). Please avoid it.

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: include/nlohmann/detail/conversions/from_json.hpp (hunk 2 above)
Comment (gregmarr) [reply include/nlohmann/detail/conversions/from_json.hpp:454]: This isn't returning `json`, it's returning `std::tuple<>`, so it would be `std::tuple<>{}` instead of `{}` if you still want that change.

Comment (nlohmann) [reply include/nlohmann/detail/conversions/from_json.hpp:454]: Oh sorry. Then never mind.

**Review by gregmarr — APPROVED** [review]

**Comment by nlohmann** [comment]
I had a look at #4530, and the issue stated

> null used to de-serialize without a problem to std::tuple<> but since throws an error since 3.10.0.

and

> Expected - null succesfully de-serializes when j.get<std::tuple<>>() is called on null.

However, when I execute this code

```cpp
// deserialize null
nlohmann::json j_null;
CHECK_NOTHROW(j_null.get<std::tuple<>>());
```

on this branch, I still get the error

```

[json.exception.type_error.302] type must be array, but is null
```

I am fine with serializing and empty tuple to `[]`, but in the end, we do not fix the linked issue, right?

**Comment by gregmarr** [comment]
The linked issue title and first two sentences:

Title
> Empty std::tuple<> cannot be serialized and de-serialized

1
> The behavior of serializing and de-sereailzing an empty tuple changed from 3.9.1 to 3.10.0.

2
> null used to de-serialize without a problem to std::tuple<> but since throws an error since 3.10.0.

So I would say it fixes the title first sentence (round trip from c++ to json to c++) by fixing the serializing.  I think it's clear that the serializing to `null` is a bug and should be fixed.

It doesn't fix the second sentence (deserialize to `std::tuple<>` from `null`).  I think the "Expected behavior" in that issue is wrong and this is desired behavior.  You can't deserialize to `std::string` or `int` from `null`, so I think it's fine that you can't deserialize it to `std::tuple<>` either.

**Comment by nlohmann** [comment]
Thanks @gregmarr. I totally agree, but I wanted to make sure to what extent we address all aspects of the issue.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by nlohmann** [comment]
Thanks!
