### PR TITLE
change bjdata ndarray flag to detect negative size, as part of #3475

### LINKED ISSUE #3475: json:parse_bjdata_fuzzer reaches assertion
### Description

The input `0x5b, 0x23, 0x49, 0x20, 0xff` triggers an assertion in the fuzzer for BJData.

- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47305
- https://oss-fuzz.com/testcase-detail/5621157828624384

### Reproduction steps

- Call the fuzzer on input `0x5b, 0x23, 0x49, 0x20, 0xff`.
- Observe the assertion.

### Expected vs. actual results

No assertion should be triggered. Either the fuzzer must be made more robust against or there is a bug in the library that must be fixed.

### Minimal code example

Adapted fuzzer:

```cpp
#include <nlohmann/json.hpp>

using json = nlohmann::json;

int main() {
    std::vector<std::uint8_t> vec1 = {{0x5b, 0x23, 0x49, 0x20, 0xff}};

    json j1 = json::from_bjdata(vec1);

    try
    {
        // step 2.1: round trip without adding size annotations to container types
        std::vector<uint8_t> vec2 = json::to_bjdata(j1, false, false);

        // step 2.2: round trip with adding size annotations but without adding type annonations to container types
        std::vector<uint8_t> vec3 = json::to_bjdata(j1, true, false);

        // step 2.3: round trip with adding size as well as type annotations to container types
        std::vector<uint8_t> vec4 = json::to_bjdata(j1, true, true);

        // parse serialization
        json j2 = json::from_bjdata(vec2);
        json j3 = json::from_bjdata(vec3);
        json j4 = json::from_bjdata(vec4);

        // serializations must match
        assert(json::to_bjdata(j2, false, false) == vec2);
        assert(json::to_bjdata(j3, true, false) == vec3);
        assert(json::to_bjdata(j4, true, true) == vec4);
    }
    catch (const json::parse_error&)
    {
        // parsing a BJData serialization must not fail
        assert(false);
    }
}
```

### Error messages

Assertion

```cpp
// parsing a BJData serialization must not fail
assert(false);
```

is triggered. In the original context, the following stack trace is produced:

```
+----------------------------------------Release Build Stacktrace----------------------------------------+
Command: /mnt/scratch0/clusterfuzz/resources/platform/linux/unshare -c -n /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds-afl_json_26b1464c0c18fac23c49bf26ed996090f90e682a/revisions/parse_bjdata_fuzzer /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash
Time ran: 0.16492581367492676
parse_bjdata_fuzzer: src/fuzzer-parse_bjdata.cpp:66: int LLVMFuzzerTestOneInput(const uint8_t *, size_t): Assertion `false' failed.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==765==ERROR: AddressSanitizer: ABRT on unknown address 0x0539000002fd (pc 0x7f986288918b bp 0x7f98629fe588 sp 0x7fff5efdeb10 T0)
SCARINESS: 10 (signal)
    #0 0x7f986288918b in raise /build/glibc-eX1tMB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:51:1
    #1 0x7f9862868858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
    #2 0x7f9862868728 in __assert_fail_base /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:92:3
    #3 0x7f9862879f35 in __assert_fail /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:101:3
    #4 0x4d9414 in LLVMFuzzerTestOneInput json/tests/src/fuzzer-parse_bjdata.cpp:66:13
    #5 0x4d729a in ExecuteFilesOnyByOne aflplusplus/utils/aflpp_driver/aflpp_driver.c:234:7
    #6 0x4d706d in main aflplusplus/utils/aflpp_driver/aflpp_driver.c:318:12
    #7 0x7f986286a0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
    #8 0x41e5bd in _start
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
==765==ABORTING
```

### Compiler and operating system

macOS 12.3.1, Apple clang version 13.1.6

### Library version

develop

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by fangq**
here is the fix to #3475. I took @falbrechtskirchinger's suggestion, and use size_and_type.second's bit 8 (all BJData nd UBJSON markers are ASCII letters) as an ND array indicator, this allows negative sizes to be thrown as `json.exception.out_of_range` error.

This should fix the detected fuzzer errors. Let me know if you still see anything.

### CODE REVIEW

**Comment by falbrechtskirchinger** [comment]
My apologies for derailing the conversation in #3475.

You have fixed an issue raised in #3475 but not *the* issue that started #3475. @nlohmann and I started talking about fuzzing in general, I discovered more failures, and then I shared one of those, which is the one you have now fixed.

Unless I'm mistaken, this doesn't fix the assertion error from the issue description? That was somehow related to `unexpect_eof()`, right?

I suggest you change the title of this PR to something more generic and we address all assertion failures discovered by fuzzing in one go. I'll share a list in #3475.

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 1]
```diff
@@ -1938,6 +1938,7 @@ class binary_reader
     {
         std::pair<std::size_t, char_int_type> size_and_type;
         size_t dimlen = 0;
+        bool isndarray = false;
```
Comment (nlohmann) [inline include/nlohmann/detail/input/binary_reader.hpp:1941]: Please rename to `is_ndarray`.

File: tests/src/unit-bjdata.cpp [hunk 2]
```diff
@@ -2488,6 +2488,27 @@ TEST_CASE("BJData")
...
+            {
+                std::vector<uint8_t> v1 = {'[', '#', 'i', 0xF1};
+                std::vector<uint8_t> v2 = {'[', '$', 'I', '#', 'i', 0xF2};
+                std::vector<uint8_t> v3 = {'[', '$', 'I', '#', '[', 'i', 0xF4, 'i', 0x02, ']'};
+                std::vector<uint8_t> v4 = {'[', '$', 0xF6, '#', 'i', 0xF7};
+                std::vector<uint8_t> v5 = {'[', '$', 'I', '#', '[', 'i', 0xF5, 'i', 0xF1, ']'};
+                std::vector<uint8_t> v6 = {'[', '#', '[', 'i', 0xF3, 'i', 0x02, ']'};
+
+                json _;
+                CHECK_THROWS_AS(_ = json::from_bjdata(v1), json::out_of_range&);
```
Comment (nlohmann) [inline tests/src/unit-bjdata.cpp:2501]: Please us `CHECK_THROWS_WITH_AS` macro (see https://github.com/doctest/doctest/blob/master/doc/markdown/assertions.md#exceptions) to check both the exception type and the diagnostic output.

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 3]
```diff
@@ -2202,12 +2205,22 @@ class binary_reader
                                         exception_message(input_format, concat("expected '#' after type information; last byte: 0x", last_token), "size"), nullptr));
             }
 
-            return get_ubjson_size_value(result.first);
+            bool iserr = get_ubjson_size_value(result.first, isndarray);
```
Comment (nlohmann) [inline include/nlohmann/detail/input/binary_reader.hpp:2208]: Rename it `is_err` or `is_error`.

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 4]
```diff
@@ -2202,12 +2205,22 @@ class binary_reader
...
+            if (input_format == input_format_t::bjdata && isndarray)
+            {
+                result.second |= 256; // use bit 8 to indicate ndarray, all UBJSON and BJData markers should be ASCII letters
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2211]: Here.

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 5]
```diff
@@ -2202,12 +2205,22 @@ class binary_reader
...
+            return iserr;
         }
 
         if (current == '#')
         {
-            return get_ubjson_size_value(result.first);
+            bool iserr = get_ubjson_size_value(result.first, isndarray);
+            if (input_format == input_format_t::bjdata && isndarray)
+            {
+                result.second |= 256; // use bit 8 to indicate ndarray, all UBJSON and BJData markers should be ASCII letters
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2221]: Here.

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 6]
```diff
@@ -2411,12 +2424,14 @@ class binary_reader
         // detect and encode bjdata ndarray as an object in JData annotated array format (https://github.com/NeuroJSON/jdata):
         // {"_ArrayType_" : "typeid", "_ArraySize_" : [n1, n2, ...], "_ArrayData_" : [v1, v2, ...]}
 
-        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.first >= (1ull << (sizeof(std::size_t) * 8 - 1)))
+        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.second >= 256)
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2427]: Here.

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 7]
```diff
@@ -2411,12 +2424,14 @@ class binary_reader
...
         {
             std::map<char_int_type, string_t> bjdtype = {{'U', "uint8"},  {'i', "int8"},  {'u', "uint16"}, {'I', "int16"},
                 {'m', "uint32"}, {'l', "int32"}, {'M', "uint64"}, {'L', "int64"}, {'d', "single"}, {'D', "double"}, {'C', "char"}
             };
 
+            size_and_type.second -= 256;
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2433]: Here.

And please add a comment to explain why,

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 8]
```diff
@@ -2508,7 +2522,7 @@ class binary_reader
             return false;
         }
 
-        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.first >= (1ull << (sizeof(std::size_t) * 8 - 1)))
+        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.second >= 256)
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2525]: Here.

**Review by falbrechtskirchinger — CHANGES_REQUESTED** [review]
I'd use `0x0100` instead of `256`. I find it to be slightly clearer but maybe that's just my embedded background. :man_shrugging:

Also please use bit operations to test and clear bit 8.

```cpp
// unfortunately we need a cast here which makes it more verbose :-(
is_ndarray = static_cast<bool>(size_and_type.second & 0x0100)

size_and_type.second &= ~0x0100;
```

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 9]
```diff
@@ -2508,7 +2522,7 @@ class binary_reader
...
         {
             return false;
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2527]: This code path needs to emit a parse error.

I'll leave message and ID to you but this is what I'm using while testing.
```cpp
            auto last_token = get_token_string();
            return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read,
                                    exception_message(input_format, "unexpected ND array size information", "object"), nullptr));
```

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 10]
```diff
@@ -2411,12 +2424,14 @@ class binary_reader
...
         {
             std::map<char_int_type, string_t> bjdtype = {{'U', "uint8"},  {'i', "int8"},  {'u', "uint16"}, {'I', "int16"},
                 {'m', "uint32"}, {'l', "int32"}, {'M', "uint64"}, {'L', "int64"}, {'d', "single"}, {'D', "double"}, {'C', "char"}
             };
 
+            size_and_type.second -= 256;
+
             string_t key = "_ArrayType_";
             if (JSON_HEDLEY_UNLIKELY(bjdtype.count(size_and_type.second) == 0 || !sax->key(key) || !sax->string(bjdtype[size_and_type.second]) ))
             {
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2437]: This needs to emit a parse error when `count() == 0`.

Once again I'll leave message and ID to you, but I'm proceeding with this fix in my continued fuzz testing:
```cpp
string_t key = "_ArrayType_";
if (JSON_HEDLEY_UNLIKELY(bjdtype.count(size_and_type.second) == 0))
{
    auto last_token = get_token_string();
    return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read, exception_message(input_format, "invalid byte: 0x" + last_token, "type"), nullptr));
}

if (JSON_HEDLEY_UNLIKELY(!sax->key(key) || !sax->string(bjdtype[size_and_type.second])))
{
    return false;
}
```

**Comment by falbrechtskirchinger** [comment]
After these changes, the only crashes that remain seem to be stack overflows.
```
Summary stats
=============

       Fuzzers alive : 10
      Total run time : 5 hours, 40 minutes
         Total execs : 253 millions
    Cumulative speed : 124093 execs/sec
       Average speed : 12409 execs/sec
       Pending items : 0 faves, 129 total
  Pending per fuzzer : 0 faves, 12 total (on average)
       Crashes saved : 10
Cycles without finds : 53/17/6/16/13/8/19/8/15/17
  Time without finds : 2 minutes, 27 seconds
```

I've built the fuzzer with ASan to confirm.
```sh
$ find fuzzer*/crashes/ -iname 'id*' -exec bash -c 'echo {}; ../fuzzer <{} |& grep -E "^SUMMARY"; echo' \;

fuzzer0/crashes/id:000000,sig:11,src:000034,time:600227,execs:7245472,op:havoc,rep:16
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer1/crashes/id:000000,sig:11,src:000007,time:602569,execs:7906177,op:havoc,rep:16
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer2/crashes/id:000000,sig:11,src:000023,time:600389,execs:7884746,op:havoc,rep:4
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer3/crashes/id:000000,sig:11,src:000006,time:602138,execs:8012670,op:havoc,rep:4
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/../sanitizer_common/sanitizer_stacktrace.h:53:45 in StackTrace

fuzzer4/crashes/id:000000,sig:11,src:000011+000001,time:602442,execs:7641057,op:splice,rep:2
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer5/crashes/id:000000,sig:11,src:000006,time:601260,execs:10537713,op:havoc,rep:16
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer6/crashes/id:000000,sig:11,src:000034+000053,time:601491,execs:7847427,op:splice,rep:16
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer7/crashes/id:000000,sig:11,src:000003,time:601378,execs:7127960,op:havoc,rep:8
SUMMARY: AddressSanitizer: stack-overflow /var/tmp/portage/sys-libs/compiler-rt-sanitizers-14.0.3/work/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset

fuzzer8/crashes/id:000000,sig:11,src:000007,time:600565,execs:7814233,op:havoc,rep:8
SUMMARY: AddressSanitizer: stack-overflow /home/flo/projects/json/issue3475/include/nlohmann/detail/input/binary_reader.hpp:2417 in nlohmann::detail::binary_reader<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > > >, nlohmann::detail::json_sax_dom_parser<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > > >::get_ubjson_array()

fuzzer9/crashes/id:000000,sig:11,src:000034+000031,time:601075,execs:7913481,op:splice,rep:16
SUMMARY: AddressSanitizer: stack-overflow /home/flo/projects/json/issue3475/include/nlohmann/detail/input/binary_reader.hpp:2417 in nlohmann::detail::binary_reader<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >, nlohmann::detail::iterator_input_adapter<__gnu_cxx::__normal_iterator<unsigned char const*, std::vector<unsigned char, std::allocator<unsigned char> > > >, nlohmann::detail::json_sax_dom_parser<nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > > >::get_ubjson_array()
```

File: tests/src/unit-bjdata.cpp (hunk 2 above)
Comment (fangq) [reply tests/src/unit-bjdata.cpp:2501]: do you prefer me to restore this (and merge `WITH` and `AS`)? the out-of-range bound seems to be platform dependent

https://github.com/NeuroJSON/json/commit/ffcf148667ddd6213d3d31958f10f7f2680374f8#diff-9c29b8711262aa7d3b188dc44aac4ba9f898a8702af3cbde1a4946191b064294L2506-L2519

msvc [did not like the condition](https://github.com/nlohmann/json/runs/6344160097?check_suite_focus=true#step:5:36), but I think I can fix that.

Comment (falbrechtskirchinger) [reply tests/src/unit-bjdata.cpp:2501]: I think you should restore those checks and fix the warning (by suppressing it with doctest macros if need be).

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 11]
```diff
@@ -2411,14 +2424,23 @@ class binary_reader
         // detect and encode bjdata ndarray as an object in JData annotated array format (https://github.com/NeuroJSON/jdata):
         // {"_ArrayType_" : "typeid", "_ArraySize_" : [n1, n2, ...], "_ArrayData_" : [v1, v2, ...]}
 
-        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.first >= (1ull << (sizeof(std::size_t) * 8 - 1)))
+        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.second >= (1 << 8))
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2427]: Use this to test if a bit is set:

```cpp
if (input_format == input_format_t::bjdata
    && size_and_type.first != string_t::npos
    && static_cast<bool>(size_and_type.second & (1 << 8)))
```

Alternatively, explicitly check for non-zero:
```cpp
(size_and_type.second & (1 << 8)) != 0
```

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 12]
```diff
@@ -2411,14 +2424,23 @@ class binary_reader
...
         {
             std::map<char_int_type, string_t> bjdtype = {{'U', "uint8"},  {'i', "int8"},  {'u', "uint16"}, {'I', "int16"},
                 {'m', "uint32"}, {'l', "int32"}, {'M', "uint64"}, {'L', "int64"}, {'d', "single"}, {'D', "double"}, {'C', "char"}
             };
 
+            size_and_type.second &= ~(1 << 8);  // use bit 8 to indicate ndarray, here we remove the bit to restore the type marker
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2433]: To address the compiler warnings, change to:
```cpp
size_and_type.second &= ~(static_cast<char_int_type>(1) << 8));
```

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 13]
```diff
@@ -2508,9 +2529,11 @@ class binary_reader
             return false;
         }
 
-        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.first >= (1ull << (sizeof(std::size_t) * 8 - 1)))
+        if (input_format == input_format_t::bjdata && size_and_type.first != string_t::npos && size_and_type.second >= (1 << 8))
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2532]: As above:

```cpp
if (input_format == input_format_t::bjdata
    && size_and_type.first != string_t::npos
    && static_cast<bool>(size_and_type.second & (1 << 8)))
```

Alternatively, explicitly check for non-zero:
```cpp
(size_and_type.second & (1 << 8)) != 0
```

**Review by falbrechtskirchinger — CHANGES_REQUESTED** [review]

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 14]
```diff
@@ -2408,17 +2421,26 @@ class binary_reader
...
             string_t key = "_ArrayType_";
-            if (JSON_HEDLEY_UNLIKELY(bjdtype.count(size_and_type.second) == 0 || !sax->key(key) || !sax->string(bjdtype[size_and_type.second]) ))
+            if (JSON_HEDLEY_UNLIKELY(bjdtype.count(size_and_type.second) == 0))
+            {
+                auto last_token = get_token_string();
+                return sax->parse_error(chars_read, last_token, parse_error::create(112, chars_read,
+                                        exception_message(input_format, "invalid byte: 0x" + last_token, "type"), nullptr));
+            }
+
+            if (JSON_HEDLEY_UNLIKELY(!sax->key(key) || !sax->string(bjdtype[size_and_type.second]) ))
```
Comment (falbrechtskirchinger) [inline include/nlohmann/detail/input/binary_reader.hpp:2443]: Test coverage has decreased because this SAX abort is untested. Can you please construct a test case for this scenario?

File: tests/src/unit-bjdata.cpp [hunk 15]
```diff
@@ -2094,6 +2094,20 @@ TEST_CASE("BJData")
...
+            CHECK(!json::sax_parse(v, &scp, json::input_format_t::bjdata));
+        }
+
+        SECTION("key() in ndarray _ArrayType_")
+        {
+            std::vector<uint8_t> v = {'[', '$', 'U', '#', '[', '$', 'U', '#', 'i', 2, 2, 2, 1, 2, 3, 4};
+            SaxCountdown scp(10);
+            CHECK(!json::sax_parse(v, &scp, json::input_format_t::bjdata));
+        }
+
```
Comment (falbrechtskirchinger) [inline tests/src/unit-bjdata.cpp:2110]: From my testing, the correct counts seem to be 6 and 7.

Please also replace all occurrences of `CHECK(!` with `CHECK_FALSE(`.

Comment (fangq) [reply tests/src/unit-bjdata.cpp:2103]: @falbrechtskirchinger, thanks. is there a way to print the event count? I previously try to many count but sometime my count does not match the expected.

Comment (falbrechtskirchinger) [reply tests/src/unit-bjdata.cpp:2103]: Not that I know off, I just step through it with the debugger.

Comment (falbrechtskirchinger) [reply tests/src/unit-bjdata.cpp:2103]: Did I give you the wrong line, or what's going on here?

https://coveralls.io/builds/48991323/source?filename=include%2Fnlohmann%2Fdetail%2Finput%2Fbinary_reader.hpp#L2456

Line 2456 is being missed now. I'm going to compare it against the previous coverage run.

Comment (falbrechtskirchinger) [reply tests/src/unit-bjdata.cpp:2103]: No, it was definitely line 2445 before.

https://coveralls.io/builds/48971838/source?filename=include%2Fnlohmann%2Fdetail%2Finput%2Fbinary_reader.hpp#L2445

:man_shrugging:

Comment (nlohmann) [reply tests/src/unit-bjdata.cpp:2117]: > @falbrechtskirchinger, thanks. is there a way to print the event count? I previously try to manually count but sometime my count does not match the expected.

Do you mean something like https://github.com/doctest/doctest/blob/master/doc/markdown/logging.md#info?

Comment (falbrechtskirchinger) [reply tests/src/unit-bjdata.cpp:2117]: I guess we could add `CHECK(m_event_count == -1)` to `~SaxEventCountdown()`. But that wouldn't solve things completely. A more advanced solution could add an enum to indicate in which event we expect the counter to reach `-1` and check if that happened in the destructor. I'll add that to my to-do list. There was another PR that moved `SaxEventCountdown` into a separate header. Probably a good idea as well.

**Review by falbrechtskirchinger — APPROVED** [review]
Looks good to me.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by nlohmann** [comment]
Thanks for fixing!
