### PR TITLE
Fixes #4854 Explicitly handle nullptr in sax_parse

### LINKED ISSUE #4854: `sax_parse` segfaults when given a null handler
### Description

Hey team,

I noticed that the `sax_parse` function family will crash with a segmentation fault if you pass `nullptr` as the SAX handler. 

The cause is a missing null check before the handler is used. You can trigger it easily:

```cpp
// This call crashes instead of throwing an exception
sax_parse(json_string, nullptr);
```

A simple guard clause at the top of the function(s) should fix it:

```cpp
// Add to all relevant sax_parse overloads
if (sax == nullptr) {
    throw json::exception("SAX handler cannot be null.");
}
```

This would make the API safer by throwing a catchable exception instead of crashing.

Thanks!

### Reproduction steps

sax_parse(json_string, nullptr);

### Expected vs. actual results

expect Exceptions vs crash

### Minimal code example

```Shell

```

### Error messages

```Shell

```

### Compiler and operating system

GCC

### Library version

latest

### Validation

- [x] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [x] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by nikhilreddydev**
Handle sax_handler nullptr exception and throw an error.
This avoids crashing of program when nullptr is passed.

#4854 

- [x] The changes are described in detail, both the what and why.
- [x] If applicable, an [existing issue](https://github.com/nlohmann/json/issues) is referenced.
- [x] The [Code coverage](https://coveralls.io/github/nlohmann/json) remained at 100%. A test case for every new line of code.
- [x] If applicable, the [documentation](https://json.nlohmann.me) is updated.
- [x] The source code is amalgamated by running `make amalgamate`.

### CODE REVIEW

File: tests/src/unit-regression2.cpp [hunk 1]
```diff
@@ -1075,6 +1153,13 @@ TEST_CASE("regression tests 2")
         CHECK(oj["test"].dump() == expected);
     }
 
+    SECTION("issue #4854 sax_parse segfaults when given a null handler")
```
Comment (gregmarr) [inline tests/src/unit-regression2.cpp]: I would think this should be in an existing SAX test file so that we don't need to duplicate the SAX class.

**Review by gregmarr — COMMENTED** [review]
You have a whole bunch of unrelated formatting changes in the headers.  Have you checked that you're using the right version of the formatting tool?

File: tests/src/unit-regression2.cpp (hunk 1 above)
Comment (nlohmann) [reply tests/src/unit-regression2.cpp]: Agree.

**Comment by nlohmann** [comment]
Please also extend https://github.com/nlohmann/json/blob/develop/docs/mkdocs/docs/home/exceptions.md#further-exceptions

**Comment by nikhilreddydev** [comment]
> You have a whole bunch of unrelated formatting changes in the headers. Have you checked that you're using the right version of the formatting tool?

Thanks for the quick review.

I have installed astyle@3.4.13 as per requirements.txt

when I try to format like below from PR source branch
`astyle --options=tools/astyle/.astylerc tests/src/unit-regression2.cpp --verbose` or
`astyle --options=tools/astyle/.astylerc include/nlohmann/json.hpp --verbose` 

It gets below unchanged output

> Artistic Style 3.4.13                             07/30/2025
> Default option file  /Users/nikhilgudi/projects/cpp/json/tools/astyle/.astylerc
>  0 formatted   1 unchanged   0.01 seconds   1,277 lines

@gregmarr could you please help me out if I'm missing something.

**Comment by nlohmann** [comment]
`make amalgamate` should do everything - including installing the required version of the tool.

**Comment by nikhilreddydev** [comment]
> `make amalgamate` should do everything - including installing the required version of the tool.

Just tried it.

Great, I think it is formatting all headers and sources.

But I could not see any changes 😄

**Comment by nlohmann** [comment]
Can you revert the changes to the header, add the line throwing the exception and try running "make amalgamate" again?

**Comment by nikhilreddydev** [comment]
> Can you revert the changes to the header, add the line throwing the exception and try running "make amalgamate" again?

Thank you! This worked.
Next, I will work on extending doc & moving test to another file as reviewed.

File: include/nlohmann/json.hpp [hunk 2]
```diff
@@ -4115,13 +4115,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
     /// @brief generate SAX events
     /// @sa https://json.nlohmann.me/api/basic_json/sax_parse/
     template <typename InputType, typename SAX>
-    JSON_HEDLEY_NON_NULL(2)
```
Comment (gregmarr) [inline include/nlohmann/json.hpp]: Is it useful to keep the non-null annotations?  It is still incorrect to pass nullptr to this function, it just now results in an explicit exception.  It's still better to catch this error early.

Comment (nlohmann) [reply include/nlohmann/json.hpp]: I think so - though it has not helped here. It seems the Hedley project is dormant. Would be great to see something similar targeting new compilers.

Comment (nikhilreddydev) [reply include/nlohmann/json.hpp]: Hello,
if I understand it correctly, the solution here is to keep both
- Hedley non-null annotations
- explicit exception handling

This has -Werror -Wtautological-pointer-compare error 

```
error: comparison of nonnull parameter 'sax' equal to a null pointer is 'false' on first encounter [-Werror,-Wtautological-pointer-compare]
 4126 |         if (sax == nullptr)
      |             ^~~    ~~~~~~~
note: in instantiation of function template specialization 'nlohmann::basic_json<>::sax_parse<std::string &, SaxCountdown>' requested here
   58 |     nlohmann::json::sax_parse(s, p);
      |                     ^
note: declared 'nonnull' here
 4119 |     JSON_HEDLEY_NON_NULL(2)
```

If suppressing this warning is the next step, may I please get some help on where actually to define this?

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Oh, that's ugly.

Comment (nikhilreddydev) [reply include/nlohmann/json.hpp]: Yes, I think it is not a good way to suppress that warning.

So, should we keep current change (removed Hedley annotations)?
Please let us know your thoughts @gregmarr  @nlohmann 
Thanks!

File: docs/mkdocs/docs/home/exceptions.md [hunk 3]
```diff
@@ -900,3 +900,15 @@ A JSON Patch operation 'test' failed. The unsuccessful operation is also printed
     ```
     [json.exception.other_error.501] unsuccessful: {"op":"test","path":"/baz","value":"bar"}
     ```
+
+### json.exception.other_error.502
+
+when sax_parse operation has failed due to sax handler being nulllptr
```
Comment (nlohmann) [inline docs/mkdocs/docs/home/exceptions.md]: Please make a complete sentence out of this. Typo: "nulllptr" -> "null pointer".

File: include/nlohmann/json.hpp [hunk 4]
```diff
@@ -4115,13 +4115,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
     static bool sax_parse(InputType&& i, SAX* sax,
                           input_format_t format = input_format_t::json,
                           const bool strict = true,
                           const bool ignore_comments = false,
                           const bool ignore_trailing_commas = false)
     {
+        if (sax == nullptr)
+        {
+            JSON_THROW(other_error::create(502, "Sax handler cannot be null", nullptr));
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
            JSON_THROW(other_error::create(502, "SAX handler must not be null", nullptr));
```

File: include/nlohmann/json.hpp [hunk 5]
```diff
@@ -4131,13 +4134,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
-    JSON_HEDLEY_NON_NULL(3)
     static bool sax_parse(IteratorType first, IteratorType last, SAX* sax,
                           input_format_t format = input_format_t::json,
                           const bool strict = true,
                           const bool ignore_comments = false,
                           const bool ignore_trailing_commas = false)
     {
+        if (sax == nullptr)
+        {
+            JSON_THROW(other_error::create(502, "Sax handler cannot be null", nullptr));
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]: See above.

File: include/nlohmann/json.hpp [hunk 6]
```diff
@@ -4151,13 +4157,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
-    JSON_HEDLEY_NON_NULL(2)
     static bool sax_parse(detail::span_input_adapter&& i, SAX* sax,
                           input_format_t format = input_format_t::json,
                           const bool strict = true,
                           const bool ignore_comments = false,
                           const bool ignore_trailing_commas = false)
     {
+        if (sax == nullptr)
+        {
+            JSON_THROW(other_error::create(502, "Sax handler cannot be null", nullptr));
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]: See above.

File: tests/src/unit-class_parser.cpp [hunk 7]
```diff
@@ -1644,6 +1644,14 @@ TEST_CASE("parser class")
 
         SECTION("SAX parser")
         {
+            SECTION("null sax handler")
+            {
+
+                std::string s = "some_string";
+                SaxCountdown* p = nullptr;
+                nlohmann::json j;
+                CHECK_THROWS_AS(j.sax_parse(s, p), json::other_error);
```
Comment (nlohmann) [inline tests/src/unit-class_parser.cpp]: Please use `CHECK_THROWS_WITH_AS` like above to check both the type of the exception and the error message.

File: docs/mkdocs/docs/home/exceptions.md [hunk 8]
```diff
@@ -900,3 +900,15 @@ A JSON Patch operation 'test' failed. The unsuccessful operation is also printed
...
+
+!!! failure "Example message"
+
+    Executing `nlohmann::json.sax_parse(some_string, nullptrHandle)`:
```
Comment (nlohmann) [inline docs/mkdocs/docs/home/exceptions.md]: Remove this line as the pseudo code is not helping here - the actual error is described above.

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: include/nlohmann/json.hpp (hunk 2 above)
Comment (nlohmann) [reply include/nlohmann/json.hpp]: Please suppress the warning and keep the Hedley annotation. The attribute is a good way to actually annotate the API whereas the runtime check is invisible.

**Comment by nlohmann** [comment]
Please rebase to the latest develop branch as I just merged #4871.

File: tests/src/unit-regression2.cpp (hunk 1 above)
Comment (nikhilreddydev) [reply tests/src/unit-regression2.cpp]: This is done https://github.com/nlohmann/json/pull/4873/commits/158c7a5bba3d0cb53c77bf0f330758adc833bc0e

File: docs/mkdocs/docs/home/exceptions.md [hunk 9]
```diff
@@ -900,3 +900,13 @@ A JSON Patch operation 'test' failed. The unsuccessful operation is also printed
     ```
     [json.exception.other_error.501] unsuccessful: {"op":"test","path":"/baz","value":"bar"}
     ```
+
+### json.exception.other_error.502
+
+This exception occurs when a null pointer is passed as SAX handler in json.sax_parse() operation.
```
Comment (nlohmann) [inline docs/mkdocs/docs/home/exceptions.md]:
```suggestion
This exception occurs when a null pointer is passed as SAX handler in [sax_parse](../api/basic_json/sax_parse.md) function.
```

File: include/nlohmann/json.hpp (hunk 5 above)
Comment (nlohmann) [reply include/nlohmann/json.hpp]: This still needs to be changed.

File: include/nlohmann/json.hpp (hunk 6 above)
Comment (nlohmann) [reply include/nlohmann/json.hpp]: This still needs to be changed.

File: tests/src/unit-class_parser.cpp [hunk 10]
```diff
@@ -1644,6 +1644,14 @@ TEST_CASE("parser class")
 
         SECTION("SAX parser")
         {
+            SECTION("null sax handler")
+            {
+
```
Comment (nlohmann) [inline tests/src/unit-class_parser.cpp]: Remove empty line.

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: tests/src/unit-class_parser.cpp (hunk 10 above)
Comment (nikhilreddydev) [reply tests/src/unit-class_parser.cpp]: Removed.

File: docs/mkdocs/docs/home/exceptions.md (hunk 8 above)
Comment (nikhilreddydev) [reply docs/mkdocs/docs/home/exceptions.md]: Removed.

File: tests/src/unit-class_parser.cpp (hunk 7 above)
Comment (nikhilreddydev) [reply tests/src/unit-class_parser.cpp]: done.

File: include/nlohmann/json.hpp [hunk 11]
```diff
@@ -4131,13 +4134,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
-    JSON_HEDLEY_NON_NULL(3)
     static bool sax_parse(IteratorType first, IteratorType last, SAX* sax,
                           input_format_t format = input_format_t::json,
                           const bool strict = true,
                           const bool ignore_comments = false,
                           const bool ignore_trailing_commas = false)
     {
+        if (sax == nullptr)
+        {
+            JSON_THROW(other_error::create(502, "Sax handler must not be null", nullptr));
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]: This string needs to be adjusted. Please also add a test that calls this function.

File: include/nlohmann/json.hpp [hunk 12]
```diff
@@ -4151,13 +4157,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
-    JSON_HEDLEY_NON_NULL(2)
     static bool sax_parse(detail::span_input_adapter&& i, SAX* sax,
                           input_format_t format = input_format_t::json,
                           const bool strict = true,
                           const bool ignore_comments = false,
                           const bool ignore_trailing_commas = false)
     {
+        if (sax == nullptr)
+        {
+            JSON_THROW(other_error::create(502, "Sax handler must not be null", nullptr));
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]: This string needs to be adjusted. Please also add a test that calls this function.

File: tests/src/unit-class_parser.cpp [hunk 13]
```diff
@@ -1644,6 +1644,14 @@ TEST_CASE("parser class")
 
         SECTION("SAX parser")
         {
+            SECTION("null sax handler")
+            {
+                std::string s = "some_string";
```
Comment (nlohmann) [inline tests/src/unit-class_parser.cpp]: Please check the output of the Clang-Tidy job - it suggests that `s` can be const.

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: include/nlohmann/json.hpp (hunk 12 above)
Comment (nikhilreddydev) [reply include/nlohmann/json.hpp]: Fixed in https://github.com/nlohmann/json/pull/4873/commits/2f6155f69e1016407b5d0e4188a29cee7dab7c15

File: include/nlohmann/json.hpp (hunk 11 above)
Comment (nikhilreddydev) [reply include/nlohmann/json.hpp]: Sorry, these string updates were missed by unsaved changes.
Fixed in https://github.com/nlohmann/json/pull/4873/commits/2f6155f69e1016407b5d0e4188a29cee7dab7c15

File: tests/src/unit-class_parser.cpp (hunk 13 above)
Comment (nikhilreddydev) [reply tests/src/unit-class_parser.cpp]: Sure, I can fix it. But I'm facing trouble setting up clang-tidy workflow on local setup

I'm using llvm & ninja. -DJSON_CI=ON
Trying to reproduce the same issues as in CI with below command
`cmake --build build --target ci_clang_tidy`

But the error it shows are very different from CI and there are a lot of warnings as errors, surprisingly if I search through them misc-const-correctness (actual error on CI) is not on local.

May I get some help on some info to setup this, If I'm missing something here.

Comment (nlohmann) [reply tests/src/unit-class_parser.cpp]: The CI runs with Clang-Tidy 21. This could be the difference. So maybe just rely on the CI and fix the issues listed in the logs.

Comment (nikhilreddydev) [reply tests/src/unit-class_parser.cpp]: Yes, maybe..
I have clang-tidy 20.1.8

Thanks!

File: tests/src/unit-class_parser.cpp [hunk 14]
```diff
@@ -1644,6 +1644,14 @@ TEST_CASE("parser class")
 
         SECTION("SAX parser")
         {
+            SECTION("null sax handler")
+            {
+                const std::string s = "some_string";
+                SaxCountdown* p = nullptr;
+                const json j;
+                CHECK_THROWS_WITH_AS(j.sax_parse(s, p), "[json.exception.other_error.502] SAX handler must not be null", json::other_error&);
```
Comment (nlohmann) [inline tests/src/unit-class_parser.cpp]: Still missing: tests for the other two overloads.

File: include/nlohmann/json.hpp [hunk 15]
```diff
@@ -4131,13 +4134,16 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
     /// @brief generate SAX events
     /// @sa https://json.nlohmann.me/api/basic_json/sax_parse/
     template<class IteratorType, class SAX>
-    JSON_HEDLEY_NON_NULL(3)
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]: Please keep these annotations, but suppress Clang's `Wtautological-pointer-compare` warning via

```cpp
#if defined(__clang__)
    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wtautological-pointer-compare"
#endif
```

and

```cpp
#if defined(__clang__)
    #pragma clang diagnostic pop
#endif
```

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: include/nlohmann/json.hpp [hunk 16]
```diff
@@ -4122,6 +4122,24 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
                           const bool ignore_trailing_commas = false)
     {
+#if defined(__clang__)
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wtautological-pointer-compare"
+#endif
+#if defined(__GNUC__) && !defined(__clang__)
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wnonnull-compare"
+#endif
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
#if defined(__clang__)
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wtautological-pointer-compare"
#elif defined(__GNUC__)
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wnonnull-compare"
#endif
```

File: include/nlohmann/json.hpp [hunk 17]
```diff
@@ -4138,6 +4156,24 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
#if defined(__clang__)
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wtautological-pointer-compare"
#elif defined(__GNUC__)
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wnonnull-compare"
#endif
```

File: include/nlohmann/json.hpp [hunk 18]
```diff
@@ -4158,6 +4194,24 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
#if defined(__clang__)
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wtautological-pointer-compare"
#elif defined(__GNUC__)
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wnonnull-compare"
#endif
```

File: include/nlohmann/json.hpp [hunk 19]
```diff
@@ -4122,6 +4122,24 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
+        if (sax == nullptr)
+        {
+            JSON_THROW(other_error::create(502, "SAX handler must not be null", nullptr));
+        }
+#if defined(__GNUC__) && !defined(__clang__)
+#pragma GCC diagnostic pop
+#endif
+#if defined (__clang__)
+#pragma clang diagnostic pop
+#endif
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
#if defined(__clang__)
  #pragma clang diagnostic pop
#elif defined(__GNUC__)
  #pragma GCC diagnostic pop
#endif
```

File: include/nlohmann/json.hpp [hunk 20]
```diff
@@ -4138,6 +4156,24 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
#if defined(__clang__)
  #pragma clang diagnostic pop
#elif defined(__GNUC__)
  #pragma GCC diagnostic pop
#endif
```

File: include/nlohmann/json.hpp [hunk 21]
```diff
@@ -4158,6 +4194,24 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]:
```suggestion
#if defined(__clang__)
  #pragma clang diagnostic pop
#elif defined(__GNUC__)
  #pragma GCC diagnostic pop
#endif
```

**Review by nlohmann — CHANGES_REQUESTED** [review]
Nearly good to go! Just some little simplifications.

**Review by nlohmann — APPROVED** [review]
Looks good to me!

**Comment by nlohmann** [comment]
Thanks a lot! I will merge once the CI is green (don't worry about Cirrus CI).

**Comment by nikhilreddydev** [comment]
> Thanks a lot! I will merge once the CI is green (don't worry about Cirrus CI).

Thanks for your patient reviews!
Looking forward to contribute more. 🙂
