### PR TITLE
Fixes #1971 (memory leak in basic_json::push_back)

### LINKED ISSUE #1971: Possible memory leak on push_back
I'm experiencing a memory leak when using push_back to add strings to a json object

Steps to reproduce:
- Use a custom allocator to track memory allocations
- Create a json object as array: json myJson = json::array_t{};
- Add a string type object with push_back: myJson.push_back(String{"Hello leaking world"});
- Destroy the json instance.
- Experience the leak.

I'm using Visual Studio 2017 on Windows 10, compiling with standard Debug configuration in x64
My latest synch on this branch was on 28/02/2020 at 15:20 CET.

I've (probably) fixed the issue by removing (on the single header file) the line 19426: val.m_type = value_t::null; from the function void push_back(basic_json&& val).

From my debugging, the issue comes from the fact that the m_value.array->push_back(std::move(val)); is invoking the basic_json(const basic_json&) instead of the basic_json(basic_json&&), which creates a copy of the source value that should still be properly delete by the allocator. My fix shouldn't affect the final result since, if the move constructor is invoked in the push_back of 19422, the move constructor will take care of marking the type of the source basic_json as null.

Hope this will be helpful!

Cheers,

Davide.

### PR DESCRIPTION
**Pull request by ArtemSarmini**
Fixes leak in `basic_json::push_back(basic_json&&)`. Old code incorrectly assumed that `std::move` moves, which is not always the case. basic_json move constructor marks argument as null anyway, so that line of code was redundant.
I also added valgrind-oriented unit test to address such situation.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [X]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [ ]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [X]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

File: test/src/unit-allocator.cpp [hunk 1]
```diff
@@ -234,3 +234,51 @@ TEST_CASE("controlled bad_alloc")
...
+    SECTION("my_allocator::construct doesn't forward")
+    {
+        using bad_alloc_json = nlohmann::basic_json<std::map,
+              std::vector,
+              std::string,
+              bool,
+              std::int64_t,
+              std::uint64_t,
+              double,
+              allocator_no_forward>;
```
Comment (dota17) [inline test/src/unit-allocator.cpp:278]: wried code format

Comment (ArtemSarmini) [reply test/src/unit-allocator.cpp:278]: I copied it from test above in the same file. Does this
```
using bad_alloc_json = nlohmann::basic_json<
    std::map, std::vector, std::string, bool, std::int64_t, std::uint64_t, double, allocator_no_forward>;
```
look better? Second line willl be 114 symbols long.

Comment (dota17) [reply test/src/unit-allocator.cpp:278]:
```
using bad_alloc_json = nlohmann::basic_json<std::map,
                                            std::vector,
                                            std::string,
                                            bool,
                                            std::int64_t,
                                            std::uint64_t,
                                            double,
                                            allocator_no_forward>;
```
I think it will be better.

**Comment by ArtemSarmini** [comment]
What do I do with this? https://travis-ci.org/github/nlohmann/json/jobs/672497870
> E: Unable to locate package g++-9
E: Couldn't find any package by regex 'g++-9'

**Comment by nlohmann** [comment]
Thanks!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Fixed a memory leak in basic_json::push_back. #1971 #2025

* * *

**Comment by ArtemSarmini** [comment]
Glad to help.
