### PR TITLE
Move lambda out of unevaluated context

### LINKED ISSUE #1225: Lambda in unevaluated context
I've seen #705 but it doesn't appear to be fixed. I'm unfortunately not on bleeding edge (xtensa gcc 5.2.0) so can't use newer gcc versions where this has been fixed. Can we fix this? I can make a PR.

```
~/code/work/esp32-core/main/json/single_include/nlohmann/json.hpp: In constructor 'nlohmann::detail::input_adapter::input_adapter(IteratorType, IteratorType)':
~/code/work/esp32-core/main/json/single_include/nlohmann/json.hpp:2165:20: error: lambda-expression in unevaluated context
                    [&first](std::pair<bool, int> res, decltype(*first) val)
```

### PR DESCRIPTION
**Pull request by mandreyel**
Fixes #1225.

As per issue #1225, the lambda has been moved out of the assert to prevent the "lambda-expression in unevaluated context" error that is present with older compilers, and has been wrapped in an `#ifdef DEBUG` directive to keep production and debug builds the same.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.8 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](http://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

File: include/nlohmann/detail/input/input_adapters.hpp [hunk 1]
```diff
@@ -320,15 +320,18 @@ class input_adapter
                  int>::type = 0>
     input_adapter(IteratorType first, IteratorType last)
     {
+#ifdef DEBUG
```
Comment (nlohmann) [inline include/nlohmann/detail/input/input_adapters.hpp]: I am sorry, I wrote it wrong in the original issue. This should be `#ifndef NDEBUG`, see https://en.cppreference.com/w/cpp/error/assert.

Comment (mandreyel) [reply include/nlohmann/detail/input/input_adapters.hpp]: Ah, that's what I thought, should have asked. Brb then!

**Comment by nlohmann** [comment]
Thanks a lot!

**Comment by mandreyel** [comment]
Thank *you* for the great lib!
