### PR TITLE
Fix C4702 warning and extend MSVC CI job

### LINKED ISSUE #4745: [MSVC] [std:c++latest] Warning C4702 after updating to json 3.12.0 with Visual Studio 2022 17.12.7
### Description

Hi,
After updating from v3.11.3 to v3.12.0 I am facing new compiler warnings when building json 3.12.0 with /std:c++ latest in Visual Studio 2022 17.12.7.

The warning '_C4702: unreachable code_'  occurs multiple times in '_include\nlohmann\detail\input\binary_header.hpp_' in function    _static void byte_swap(NumberType& number)_ in lines 2831, 2835, 2836, 2838.

Issue is still existing latest version of development branch.

### Reproduction steps

1. Download json-3.12.0.zip and unzip
2. Open a Developer command Prompt v17.12.7
3. cd json-3.12.0
4. Create directory _build_ and cd build
5. cmake ..\ -D  CMAKE_CXX_FLAGS="/std:c++latest"
6. cmake --build .

### Expected vs. actual results

No warnings expected.

Currently multiple C4702 warnings: unreachable code.

### Minimal code example

```Shell

```

### Error messages

```Shell
e.g.
  unit-locale-cpp.cpp
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2831,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2831,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2835,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2836,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
[...]\include\nlohmann\detail\input\binary_reader.hpp(2838,1): warning C4702: unreachable code [[...]\build\tests\test-locale-cpp_cpp11.vcxproj]
  test-locale-cpp_cpp11.vcxproj -> [...]\build\tests\Debug\test-locale-cpp_cpp11.exe
```

### Compiler and operating system

Microsoft Visual Studio 2022 17.12.7, Windows 11 24H2

### Library version

3.12.0

### Validation

- [x] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by nlohmann**
- Add release/debug matrix step to MSVC job to detect warnings as reported in #4745
- Simplified MSVC 2019/2022 job.
- Fixes C4702 warning in binary reader code (thanks @gregmarr).

Closes #4745

### CODE REVIEW

**Comment by simonedi** [comment]
Looks good for me. No warnings occurring anymore.

File: include/nlohmann/detail/input/binary_reader.hpp [hunk 1]
```diff
@@ -2826,17 +2826,22 @@ class binary_reader
...
+        else
         {
-            std::swap(ptr[i], ptr[sz - i - 1]);
+#endif
+            auto* ptr = reinterpret_cast<std::uint8_t*>(&number);
+            for (std::size_t i = 0; i < sz / 2; ++i)
+            {
+                std::swap(ptr[i], ptr[sz - i - 1]);
+            }
+#ifdef __cpp_lib_byteswap
```
Comment (gregmarr) [inline include/nlohmann/detail/input/binary_reader.hpp:2842]: Not sure if this was a style preference, or if it confused one of the formatters, but you can simplify this a little by not having the braces be inside the ifdef.  As it is here, you have the potential for the two ifdef statements to get out of sync.

Comment (nlohmann) [reply include/nlohmann/detail/input/binary_reader.hpp:2842]: cpplint complained, and I thought "fixing" it was less effort than silencing it.

Comment (gregmarr) [reply include/nlohmann/detail/input/binary_reader.hpp:2842]: Agreed

**Review by gregmarr — APPROVED** [review]
