### PR TITLE
Provide a from_json overload for std::map

### LINKED ISSUE #1079: Compilation error with strong typed enums in map in combination with namespaces
- What is the issue you have?
Compilation error.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?
Compiling the small program below results in C2166: l-value specifies const object (see full compiler output below). When putting the map and the to/from_json in the same namespace it compiles. It boilds down to an assignment/construction of the map's value type.
```
#include <json/json.hpp>
#include <map>
#include <string>

namespace bla
{
enum class foo : uint16_t
{
	bar, baz
};
} // comment this out and the lines above main in and it will compile
using foo_map = std::map<foo, std::string>;

void to_json(nlohmann::json& j, const foo_map& m)
{

}

void from_json(const nlohmann::json& j, foo_map& m)
{

}
//}
//using bla::foo_map;
int main(int, char**)
{
	nlohmann::json j;
	foo_map m = j;
}
```

- What is the expected behavior?
It should compile without errors 

- And what is the actual behavior instead?
Compilation errors
```
compiling main.cpp
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX64/x64/cl.exe /nologo /c /EHsc /Od /Zi /MDd "/IC:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\ipp\include" /IC:\Qt\Qt5.9.5\5.9.5\msvc2017_64\include /IC:\Qt\Qt5.9.5\5.9.5\msvc2017_64\include\QtCore /IC:\Qt\Qt5.9.5\5.9.5\msvc2017_64\mkspecs\win32-msvc /IC:\Projekte\monalysis\Entwicklung\Quellen\Projekte\build-scratchpad-VC17ohneQt-Debug\qtc_VC17_91031919-debug\scratchpad.a434f584\qt.headers /IC:\Projekte\thirdparty\boost /IC:\Projekte\thirdparty\fmt /IC:\Projekte\thirdparty\json /IC:\Projekte\thirdparty\nonius\nonius /IC:\Projekte\thirdparty\range-v3\range-v3-vs2015\include /DUNICODE /D_UNICODE /DWIN32 /DQT_CORE_LIB /DBOOST_LIB_DIAGNOSTIC /DBOOST_AUTO_LINK_TAGGED /DBOOST_RESULT_OF_USE_DECLTYPE /DBOOST_QT_PUSHBACK_WORKAROUND "/DBOOST_QT_LISTOF_WORKAROUND=1" "/DWINVER=0x0502" "/D_WIN32_WINNT=0x0502" "/D_WIN32_WINDOWS=0x0502" /FoC:\Projekte\monalysis\Entwicklung\Quellen\Projekte\build-scratchpad-VC17ohneQt-Debug\qtc_VC17_91031919-debug\scratchpad.a434f584\3a52ce780950d4d9\main.cpp.obj C:\Projekte\monalysis\Entwicklung\Quellen\Projekte\scratchpad\main.cpp /TP /FS /permissive- /std:c++latest /Zm200
:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\utility(268): error C2166: l-value specifies const object
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\utility(267): note: while compiling class template member function 'std::pair<const _Kty,_Ty> &std::pair<const _Kty,_Ty>::operator =(std::pair<const _Kty,_Ty> &&) noexcept(false)'
        with
        [
            _Kty=bla::foo,
            _Ty=std::string
        ]
C:\Projekte\monalysis\Entwicklung\Quellen\Projekte\monalysis-porsche\thirdparty\json\json/json.hpp(1172): note: see reference to function template instantiation 'std::pair<const _Kty,_Ty> &std::pair<const _Kty,_Ty>::operator =(std::pair<const _Kty,_Ty> &&) noexcept(false)' being compiled
        with
        [
            _Kty=bla::foo,
            _Ty=std::string
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(443): note: see reference to class template instantiation 'std::pair<const _Kty,_Ty>' being compiled
        with
        [
            _Kty=bla::foo,
            _Ty=std::string
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(739): note: see reference to class template instantiation 'std::_Tree_node<std::pair<const _Kty,_Ty>,std::_Default_allocator_traits<_Alloc>::void_pointer>' being compiled
        with
        [
            _Kty=bla::foo,
            _Ty=std::string,
            _Alloc=std::allocator<std::pair<const bla::foo,std::string>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(738): note: while compiling class template member function 'void std::_Tree_comp_alloc<_Traits>::_Freeheadnode(std::_Tree_node<std::pair<const _Kty,_Ty>,std::_Default_allocator_traits<_Alloc>::void_pointer> *)'
        with
        [
            _Traits=std::_Tmap_traits<bla::foo,std::string,std::less<bla::foo>,std::allocator<std::pair<const bla::foo,std::string>>,false>,
            _Kty=bla::foo,
            _Ty=std::string,
            _Alloc=std::allocator<std::pair<const bla::foo,std::string>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(631): note: see reference to function template instantiation 'void std::_Tree_comp_alloc<_Traits>::_Freeheadnode(std::_Tree_node<std::pair<const _Kty,_Ty>,std::_Default_allocator_traits<_Alloc>::void_pointer> *)' being compiled
        with
        [
            _Traits=std::_Tmap_traits<bla::foo,std::string,std::less<bla::foo>,std::allocator<std::pair<const bla::foo,std::string>>,false>,
            _Kty=bla::foo,
            _Ty=std::string,
            _Alloc=std::allocator<std::pair<const bla::foo,std::string>>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(842): note: see reference to class template instantiation 'std::_Tree_comp_alloc<_Traits>' being compiled
        with
        [
            _Traits=std::_Tmap_traits<bla::foo,std::string,std::less<bla::foo>,std::allocator<std::pair<const bla::foo,std::string>>,false>
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\map(81): note: see reference to class template instantiation 'std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>' being compiled
        with
        [
            _Kty=bla::foo,
            _Ty=std::string,
            _Pr=std::less<bla::foo>,
            _Alloc=std::allocator<std::pair<const bla::foo,std::string>>
        ]
C:\Projekte\monalysis\Entwicklung\Quellen\Projekte\scratchpad\main.cpp(212): note: see reference to class template instantiation 'std::map<bla::foo,std::string,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>' being compiled
        with
        [
            _Kty=bla::foo,
            _Ty=std::string
        ]
```

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
MSVC 2017 (15.6.6); MSVC 19.0.24215.1 (CMake output)
Not directly supported.

- Did you use a released version of the library or the version from the `develop` branch?
Release 3.1.2

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?
Tried but ctest gives error `Test not available without configuration.  (Missing "-C <config>"?)` for every test case. If told how to fix this I'll happily execute the tests.

### PR DESCRIPTION
**Pull request by theodelrieu**
This overload is chosen only when BasicJsonType::string_t
is not constructible from std::map::key_type.

Currently, converting a map to json treats it as an array of pairs.

fixes #1079 

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

### CODE REVIEW

**Comment by theodelrieu** [comment]
@nlohmann Since we don't check extra values in the array when converting to `std::pair`, I'm doing the same thing.

(i.e. `[1,2,3,4]` -> `std::pair {1, 2}`)

I'm wondering if we should check if the insertion in the map was successful, seems like a good idea. I don't know which exception to throw however. What's your opinion on it?

**Comment by nlohmann** [comment]
Sorry, I haven't found the time to look into this earlier.

File: test/src/unit-conversions.cpp [hunk 1]
```diff
@@ -1079,6 +1079,18 @@ TEST_CASE("value conversion")
...
+            SECTION("std::map (array of pairs)")
+            {
+                std::map<int, int> m{{0, 1}, {1, 2}, {2, 3}};
+                json j6 = m;
+
+                auto m2 = j6.get<std::map<int, int>>();
+                CHECK(m == m2);
+
+                json j7 = {0, 1, 2, 3};
+                CHECK_THROWS_WITH((j7.get<std::map<int, int>>()), "[json.exception.type_error.302] type must be array, but is number");
```
Comment (nlohmann) [inline test/src/unit-conversions.cpp]: Could you please also add a `CHECK_THROWS_AS` test?

**Comment by nlohmann** [comment]
I think the behavior is OK as you're right: it is consistent to the `std::pair` treatment. Adding an exception for `std::map` would also require adding one for `std::pair` which would mean a breaking change in terms of semantic versioning, right?

File: test/src/unit-conversions.cpp (hunk 1 above)
Comment (theodelrieu) [reply test/src/unit-conversions.cpp]: Done

**Comment by theodelrieu** [comment]
Nothing is breaking, unless I missed something.

The `std::pair` overload is already there, and does not need to be changed. The issue with `std::map` is that its `value_type` is `std::pair<**const** Key, Value>`, so using the default `std::pair` overload does not work.

The only way that I know of constructor this peculiar `value_type` is to use `std::map` constructors/functions, so this special treatment is done inside the `std::map` overload.

Also, one can already serialize a `std::map<int, int>` to json, the other way around does not work though.

**Comment by nlohmann** [comment]
With "breaking" I meant the API behavior in case of superfluous list entries. As we do not throw for pairs if we convert from a 3-element list, we should not throw for maps for symmetry reasons. But adding an exception to the pairs would be a breaking change.

**Comment by theodelrieu** [comment]
Oh you're right, I've added a test case for this, I kept the existing behavior (i.e. discarding extra values from arrays)

**Comment by nlohmann** [comment]
Just for my understanding: Assume I have `MyType` and provided a `to_json` function. Then `std::map<int, MyType>` will be serialized to a list of pairs, and `std::map<std::string, MyType>` will be serialized to an object.

Assume I have `AnotherType` that can be converted to a `std::string`, e.g. by `operator std::string()`. Will a `std::map<AnotherType, MyType` be serialized to an object?

**Comment by theodelrieu** [comment]
Indeed, it will be serialized to an object.

The condition is: if `string_t` is constructible from `Key`, then it will be serialized to an object.

**Comment by nlohmann** [comment]
Thanks a lot!
