### PR TITLE
Fix NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT with an empty JSON instance

### LINKED ISSUE #4507: NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT throw an exception with an empty json
### Description

NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT should not throw an exception when the json instance is empty and should use the default values of the member fields

### Reproduction steps

run the Minimal code example and get the exception

### Expected vs. actual results

don't expect to get exception with an empty JSON
expect that foo member fields are filled with they default values

### Minimal code example

```Shell
class Foo {
 public:
  NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT(Foo, a, b)

  Foo() = default;

  int a{10};
  std::string b{"bar"};

  void log() {
    std::cout << "a: " << a << std::endl;
    std::cout << "b: " << b << std::endl;
  }
};

// with an empty json, an exception is thrown instead of getting default values
static void JsonTest_empty_json() {
  nlohmann::json json{};
  auto foo = Foo(json);
  foo.log();
}

int main(int argc, char **argv) {
  JsonTest_empty_json();
  return 0;
}
```

### Error messages

_No response_

### Compiler and operating system

clang++ / C++17 / Windows OS

### Library version

ref: v3.11.2 - commit: 7d2f9ad500cf062394040f44d006791ff7cfc1c1

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

### PR DESCRIPTION
**Pull request by NissimBendanan**
Do not throw an exception when trying to get default value from empty json
fix the issue #4507

```
class Foo {
 public:
  NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT(Foo, a, b)

  Foo() = default;

  int a{10};
  std::string b{"bar"};

  void log() {
    std::cout << "a: " << a << std::endl;
    std::cout << "b: " << b << std::endl;
  }
};

// with an empty json, an exception is thrown instead of getting default values
static void JsonTest_empty_json() {
  nlohmann::json json{};
  auto foo = Foo(json);
  foo.log();
}
```

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [x]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for this kind of bug). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](https://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

File: include/nlohmann/json.hpp [hunk 1]
```diff
@@ -2237,6 +2237,10 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
 
             return default_value;
         }
+        else if (JSON_HEDLEY_LIKELY(is_null()))
```
Comment (nlohmann) [inline include/nlohmann/json.hpp]: Please don't change the behavior of the `value` function. This would break the API.

**Review by nlohmann — CHANGES_REQUESTED** [review]

**Comment by nlohmann** [comment]
Please also check #4323.

File: include/nlohmann/json.hpp (hunk 1 above)
Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: All the PR is about this change.
Which API may be broken?

Comment (nlohmann) [reply include/nlohmann/json.hpp]: No. The issue is that when `NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT` is applied to an empty JSON value, there is a problem. You changed the behavior of the `value` function which may be called by the macro, but is also a public API function.

From its documentation (https://json.nlohmann.me/api/basic_json/value/#parameters):

> [The function throws] [type_error.306](https://json.nlohmann.me/home/exceptions/#jsonexceptiontype_error306) if the JSON value is not an object; in that case, using value() with a key makes no sense.

Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: ok, I got your point, so the fix should be in NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT and its other variants, right?

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Maybe, but that's still changing the behavior of classes using these macros, which were introduced in January 2022, and released in 3.11.0 in August of 2022, so they've been part of 4 releases over the last 2+ years.

```
It will not throw an exception in `from_json()` due to a missing value in the JSON object, but can throw due to a mismatched type. The `from_json()` function default constructs an object and uses its values as the defaults when calling the `value()` function.
```

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Oh, this isn't the error that I thought it was.  I thought it was `from_json` on trying to get `a` and `b` from `{ "a": null, "b": null }`, not `{}`.  This would actually work properly on `{ "c": "foo" }`.

In this case, I think it would be okay for `from_json` to check for the root `json` being `null` instead of an object.

Comment (gregmarr) [reply include/nlohmann/json.hpp]:
```
#define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1);
```
Maybe this, which matches the current documented behavior?
```
#define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = !nlohmann_json_j.is_null() ? nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1) : nlohmann_json_default_obj.v1;
```

Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: yes, this is fixing my issue :)

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Okay, so how did you actually get to this condition?  Is there some reason that you can't check that the `json` object is empty first before creating `Foo` from it?  I assume it's part of a larger document and object model.  I'm wondering if there is a higher level where this could be avoided.

Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: I get to this condition while deserialazing a wrong json content.
In this case the json instance is discarded, so instead we wanted to use an empty one with `json = {}`
then we get an exception instead of getting default values in Foo constructor

so: using a json instance with bar content instead of foo content is working,
but: using a json instance empty without bar content nor foo content is throwing exception

IMHO: json = {} is a valid and legal constructor

```
static void JsonTest_parse(std::string content) {
  // with an empty_content or an invalid_content, json is discarded
  auto json = nlohmann::json::parse(content, nullptr, false);
  if (json.is_discarded()) {
    LOG_ERROR("Failed to parse: {}", content);
    // here wanted to build a new empty json
    json = {};  // set custom config to empty
  }
  // an exception is thrown instead of getting default values
  auto foo = Foo(json);
  foo.log();
};

// with an empty json, an exception is thrown instead of getting default values
static void JsonTest_empty_json() {

  // this is OK to parse a content with bar instead of foo
  std::string valid_content{R"({"bar": true})"};
  JsonTest_parse(valid_content);

  // both tests empty_content and invalid_content are discarded
  // and can't build Foo with its default values
  std::string empty_content{""};
  JsonTest_parse(empty_content);

  std::string invalid_content{R"({xxx "bar": true})"};
  JsonTest_parse(invalid_content);
}
```

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Is there some reason that you can't just create the default object instead of constructing it from an empty json object?  I assume that the code you shared is just testing this particular issue, and is not representative of your actual code.  If it is representative, you can just do this:

```
static void JsonTest_parse(std::string content) {
  // with an empty_content or an invalid_content, json is discarded
  auto json = nlohmann::json::parse(content, nullptr, false);

  Foo foo;
  if (!json.is_discarded()) {
    foo = json;
  } else {
    LOG_ERROR("Failed to parse: {}", content);
  }
  foo.log();
};
```

Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: yes we can, and there are plenty of options to solve this, but:

> API is like a joke. If you have to explain it, it’s not that good.

`NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT` should means that if the key is not found during deserialization the defaults will be used.

Why artificially limit it? This adds complexity for the API users while not providing any clear benefits

Comment (gregmarr) [reply include/nlohmann/json.hpp]: That's exactly what it means, but it currently has a precondition that the place where you are looking for the key is actually something that can contain a key.  Now, it's at least true here that this is just looking to handle it for a `null`, which has no data, so it's reasonable to make that change to relax the precondition a bit.

What I'm wondering, however, is if your actual code is doing exactly what you are showing here, and intentionally creating an empty `json` object and manually using it to create the `Foo` object, in which case it seems like the best way to fix that immediately is to not do that.

If this is just reproducing a smaller part of a larger system where you are getting a `null` instead of an `object` in a larger JSON string, and assigning it to `Foo` inside a larger data structure, then there may be something to be done even one level higher in your code so that you never even hit trying to create `Foo` from the empty `json`.

Both of those fixes are more immediately applicable to your code than updating this library and waiting for a new release.

Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: Yes we made the necessary changes in our code to not try to use an empty JSON.
For the library, we should make this change, would you agree?

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Great, I'm glad that has been resolved for you.  I do think that's a useful change, and it makes the implementation better match the documented behavior of the function.  @nlohmann will need to make the final decision on that.

Comment (nlohmann) [reply include/nlohmann/json.hpp]: I would need to see what's changed in the end. If this is about fixing the behavior of a macro, then I'm in. If it's about changing the behavior of an existing public API function, then I am out.

Comment (gregmarr) [reply include/nlohmann/json.hpp]: Yes, just this change to the macro:
https://github.com/nlohmann/json/pull/4508#discussion_r1852637742

```
#define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1)
```

From
```
nlohmann_json_t.v1 = nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1);
```

To
```
nlohmann_json_t.v1 = !nlohmann_json_j.is_null() ? nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1) : nlohmann_json_default_obj.v1;
```

Comment (NissimBendanan) [reply include/nlohmann/json.hpp]: only this macro as https://github.com/nlohmann/json/pull/4508#discussion_r1852637742

```
#define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = !nlohmann_json_j.is_null() ? nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1) : nlohmann_json_default_obj.v1;
```

**Comment by NissimBendanan** [comment]
@gregmarr I will update the PR according to our decision to change only this macro NLOHMANN_JSON_FROM_WITH_DEFAULT

I will change only this file: include\nlohmann\detail\macro_scope.hpp
I will not touch this one: single_include\nlohmann\json.hpp
right?

should also add a test case or update a previous one?
any clue to do this? in which file? how to compile/run the tests?

Thanks

**Comment by gregmarr** [comment]
@NissimBendanan 
From the checklist in the PR template:
>The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header files `single_include/nlohmann/json.hpp` and `single_include/nlohmann/json_fwd.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

**Comment by gregmarr** [comment]
`NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT` is tested in https://github.com/nlohmann/json/blob/develop/tests/src/unit-udt_macro.cpp

**Comment by NissimBendanan** [comment]
I pushed a new version where I added a check of an empty json.
@nlohmann @gregmarr can you please review?
Thanks

**Comment by NissimBendanan** [comment]
I don't understand how to get rid of those errors. here in Amalgamation check failed! 🔴

Format (1)
2754c2754
< #define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1);
---
> #define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = !nlohmann_json_j.is_null() ? nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1) : nlohmann_json_default_obj.v1;
Error: Process completed with exit code 1.

locally the single_include files are generated with success.
so so how to fix all of those errors?

**Comment by nlohmann** [comment]
Use Astyle 3.1 and run make amalgamate.

**Comment by NissimBendanan** [comment]
I am using astyle 3.1:

nbendana@tlv-wp4ww:~/Projects/json$ astyle --version
Artistic Style Version 3.1
nbendana@tlv-wp4ww:~/Projects/json$ make amalgamate
make pretty
make[1]: Entering directory '/home/nbendana/Projects/json'
astyle \
    --style=allman \
    --indent=spaces=4 \
    --indent-modifiers \
    --indent-switches \
    --indent-preproc-block \
    --indent-preproc-define \
    --indent-col1-comments \
    --pad-oper \
    --pad-header \
    --align-pointer=type \
    --align-reference=type \
    --add-braces \
    --convert-tabs \
    --close-templates \
    --lineend=linux \
    --preserve-date \
    --suffix=none \
    --formatted \
   include/nlohmann/adl_serializer.hpp include/nlohmann/byte_container_with_subtype.hpp include/nlohmann/detail/abi_macros.hpp include/nlohmann/detail/conversions/from_json.hpp include/nlohmann/detail/conversions/to_chars.hpp include/nlohmann/detail/conversions/to_json.hpp include/nlohmann/detail/exceptions.hpp include/nlohmann/detail/hash.hpp include/nlohmann/detail/input/binary_reader.hpp include/nlohmann/detail/input/input_adapters.hpp include/nlohmann/detail/input/json_sax.hpp include/nlohmann/detail/input/lexer.hpp include/nlohmann/detail/input/parser.hpp include/nlohmann/detail/input/position_t.hpp include/nlohmann/detail/iterators/internal_iterator.hpp include/nlohmann/detail/iterators/iter_impl.hpp include/nlohmann/detail/iterators/iteration_proxy.hpp include/nlohmann/detail/iterators/iterator_traits.hpp include/nlohmann/detail/iterators/json_reverse_iterator.hpp include/nlohmann/detail/iterators/primitive_iterator.hpp include/nlohmann/detail/json_custom_base_class.hpp include/nlohmann/detail/json_pointer.hpp include/nlohmann/detail/json_ref.hpp include/nlohmann/detail/macro_scope.hpp include/nlohmann/detail/macro_unscope.hpp include/nlohmann/detail/meta/call_std/begin.hpp include/nlohmann/detail/meta/call_std/end.hpp include/nlohmann/detail/meta/cpp_future.hpp include/nlohmann/detail/meta/detected.hpp include/nlohmann/detail/meta/identity_tag.hpp include/nlohmann/detail/meta/is_sax.hpp include/nlohmann/detail/meta/std_fs.hpp include/nlohmann/detail/meta/type_traits.hpp include/nlohmann/detail/meta/void_t.hpp include/nlohmann/detail/output/binary_writer.hpp include/nlohmann/detail/output/output_adapters.hpp include/nlohmann/detail/output/serializer.hpp include/nlohmann/detail/string_concat.hpp include/nlohmann/detail/string_escape.hpp include/nlohmann/detail/value_t.hpp include/nlohmann/json.hpp include/nlohmann/json_fwd.hpp include/nlohmann/ordered_map.hpp include/nlohmann/thirdparty/hedley/hedley.hpp include/nlohmann/thirdparty/hedley/hedley_undef.hpp tests/abi/config/config.hpp tests/abi/config/custom.cpp tests/abi/config/default.cpp tests/abi/config/noversion.cpp tests/abi/diag/diag.cpp tests/abi/diag/diag.hpp tests/abi/diag/diag_off.cpp tests/abi/diag/diag_on.cpp tests/abi/inline_ns/use_current.cpp tests/abi/inline_ns/use_v3_10_5.cpp tests/abi/main.cpp tests/benchmarks/src/benchmarks.cpp tests/cmake_add_subdirectory/project/main.cpp tests/cmake_fetch_content/project/main.cpp tests/cmake_fetch_content2/project/main.cpp tests/cmake_import/project/main.cpp tests/cmake_import_minver/project/main.cpp tests/cmake_target_include_directories/project/Bar.cpp tests/cmake_target_include_directories/project/Bar.hpp tests/cmake_target_include_directories/project/Foo.cpp tests/cmake_target_include_directories/project/Foo.hpp tests/cmake_target_include_directories/project/main.cpp tests/cuda_example/json_cuda.cu tests/src/fuzzer-driver_afl.cpp tests/src/fuzzer-parse_bjdata.cpp tests/src/fuzzer-parse_bson.cpp tests/src/fuzzer-parse_cbor.cpp tests/src/fuzzer-parse_json.cpp tests/src/fuzzer-parse_msgpack.cpp tests/src/fuzzer-parse_ubjson.cpp tests/src/make_test_data_available.hpp tests/src/test_utils.hpp tests/src/unit-32bit.cpp tests/src/unit-algorithms.cpp tests/src/unit-allocator.cpp tests/src/unit-alt-string.cpp tests/src/unit-assert_macro.cpp tests/src/unit-binary_formats.cpp tests/src/unit-bjdata.cpp tests/src/unit-bson.cpp tests/src/unit-byte_container_with_subtype.cpp tests/src/unit-capacity.cpp tests/src/unit-cbor.cpp tests/src/unit-class_const_iterator.cpp tests/src/unit-class_iterator.cpp tests/src/unit-class_lexer.cpp tests/src/unit-class_parser.cpp tests/src/unit-comparison.cpp tests/src/unit-concepts.cpp tests/src/unit-constructor1.cpp tests/src/unit-constructor2.cpp tests/src/unit-convenience.cpp tests/src/unit-conversions.cpp tests/src/unit-custom-base-class.cpp tests/src/unit-deserialization.cpp tests/src/unit-diagnostics.cpp tests/src/unit-disabled_exceptions.cpp tests/src/unit-element_access1.cpp tests/src/unit-element_access2.cpp tests/src/unit-hash.cpp tests/src/unit-inspection.cpp tests/src/unit-items.cpp tests/src/unit-iterators1.cpp tests/src/unit-iterators2.cpp tests/src/unit-json_patch.cpp tests/src/unit-json_pointer.cpp tests/src/unit-large_json.cpp tests/src/unit-merge_patch.cpp tests/src/unit-meta.cpp tests/src/unit-modifiers.cpp tests/src/unit-msgpack.cpp tests/src/unit-no-mem-leak-on-adl-serialize.cpp tests/src/unit-noexcept.cpp tests/src/unit-ordered_json.cpp tests/src/unit-ordered_map.cpp tests/src/unit-pointer_access.cpp tests/src/unit-readme.cpp tests/src/unit-reference_access.cpp tests/src/unit-regression1.cpp tests/src/unit-regression2.cpp tests/src/unit-serialization.cpp tests/src/unit-testsuites.cpp tests/src/unit-to_chars.cpp tests/src/unit-type_traits.cpp tests/src/unit-ubjson.cpp tests/src/unit-udl.cpp tests/src/unit-udt.cpp tests/src/unit-udt_macro.cpp tests/src/unit-unicode1.cpp tests/src/unit-unicode2.cpp tests/src/unit-unicode3.cpp tests/src/unit-unicode4.cpp tests/src/unit-unicode5.cpp tests/src/unit-user_defined_input.cpp tests/src/unit-windows_h.cpp tests/src/unit-wstring.cpp tests/src/unit.cpp single_include/nlohmann/json.hpp single_include/nlohmann/json_fwd.hpp docs/examples/*.cpp
make[1]: Leaving directory '/home/nbendana/Projects/json'
nbendana@tlv-wp4ww:~/Projects/json$

**Comment by NissimBendanan** [comment]
for this failure:

[ci_static_analysis (ci_test_amalgamation)](https://github.com/nlohmann/json/actions/runs/12504473107/job/34886850454?pr=4508#logs)

I run locally without error:

```
nbendana@tlv-wp4ww:~/Projects/json$ cmake -S . -B build -DJSON_CI=On
-- Found Python3: /usr/bin/python3 (found version "3.12.3") found components: Interpreter 
-- 🔖 Artistic Style 3.1 (/usr/bin/astyle)
-- 🔖 Clang 18.1.3 (/usr/bin/clang++)
-- 🔖 Clang-Tidy 18.1.3 (/usr/bin/clang-tidy)
-- 🔖 CMake 3.28.3 (/usr/bin/cmake)
-- 🔖 Cppcheck  (CPPCHECK_TOOL-NOTFOUND)
-- 🔖 GCC 13.3.0 (/usr/bin/g++-13)
-- 🔖 GCOV 13.3.0 (/usr/bin/gcov)
-- 🔖 Git 2.43.0 (/usr/bin/git)
-- 🔖 include-what-you-use  (IWYU_TOOL-NOTFOUND)
-- 🔖 Infer  (INFER_TOOL-NOTFOUND)
-- 🔖 LCOV  (LCOV_TOOL-NOTFOUND)
-- 🔖 Ninja 1.11.1 (/usr/bin/ninja)
-- 🔖 OCLint  (OCLINT_TOOL-NOTFOUND)
-- 🔖 Valgrind  (VALGRIND_TOOL-NOTFOUND)
-- Using the multi-header code from /home/nbendana/Projects/json/include/
-- Operating system: Linux-5.15.167.4-microsoft-standard-WSL2; Distributor ID:  Ubuntu; Description:    Ubuntu 24.04.1 LTS; Release:    24.04; Codename:        noble; Linux tlv-wp4ww 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
-- Compiler: c++ (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0; Copyright (C) 2023 Free Software Foundation, Inc.; This is free software; see the source for copying conditions.  There is NO; warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-- Testing standards: 11 14 17 20 23
-- Configuring done (3.7s)
-- Generating done (0.3s)
-- Build files have been written to: /home/nbendana/Projects/json/build
nbendana@tlv-wp4ww:~/Projects/json$ cmake --build build --target ci_test_amalgamation
Check amalgamation and indentation
Creating amalgamation:
 - processing "include/nlohmann/json.hpp"
...done!


Creating amalgamation:
 - processing "include/nlohmann/json_fwd.hpp"
...done!


Built target ci_test_amalgamation
nbendana@tlv-wp4ww:~/Projects/json$ 
```

**Comment by nlohmann** [comment]
I am working on #4573 to fix the astyle call.

**Comment by nlohmann** [comment]
#4573 is merged now. Please update to the latest develop branch and try again.

**Comment by NissimBendanan** [comment]
after updating with last version, I still have this error:

```
Formatted  /home/runner/work/json/json/single_include/nlohmann/json.hpp
2764c2764
< #define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1);
---
> #define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = !nlohmann_json_j.is_null() ? nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1) : nlohmann_json_default_obj.v1;
gmake[3]: *** [CMakeFiles/ci_test_amalgamation.dir/build.make:80: CMakeFiles/ci_test_amalgamation] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:1484: CMakeFiles/ci_test_amalgamation.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1491: CMakeFiles/ci_test_amalgamation.dir/rule] Error 2
gmake: *** [Makefile:511: ci_test_amalgamation] Error 2
```
Can you please explain what does this error mean? which check generate this error? how to get rid of it?
Thanks

**Comment by nlohmann** [comment]
You only changed the code in the `include` folder. From this, the single-header sources in `single_include` need to be created. This is done by calling `make amalgamate`. Please execute this step and commit the changes.

**Comment by NissimBendanan** [comment]
so I need **also** to commit the change in single_include/nlohmann/json.hpp ?
From `CONTRIBUTING.md` it is not clear that I need to commit the changes of this file, just that it is auto generated ...

**Comment by nlohmann** [comment]
The contribution guidelines state:

> Please do not edit the files single_include/nlohmann/json.hpp and single_include/nlohmann/json_fwd.hpp directly, but change the include/nlohmann sources and regenerate the files by executing `make amalgamate`.

I am currently revising the guidelines to make this more clear.

File: include/nlohmann/detail/macro_scope.hpp [hunk 2]
```diff
@@ -395,7 +395,7 @@
 
 #define NLOHMANN_JSON_TO(v1) nlohmann_json_j[#v1] = nlohmann_json_t.v1;
 #define NLOHMANN_JSON_FROM(v1) nlohmann_json_j.at(#v1).get_to(nlohmann_json_t.v1);
-#define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1);
+#define NLOHMANN_JSON_FROM_WITH_DEFAULT(v1) nlohmann_json_t.v1 = !nlohmann_json_j.is_null() ? nlohmann_json_j.value(#v1, nlohmann_json_default_obj.v1) : nlohmann_json_default_obj.v1;
```
Comment (nlohmann) [inline include/nlohmann/detail/macro_scope.hpp:398]: Can you please also adjust `NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT` to keep the symmetry between the macros?

**Review by nlohmann — CHANGES_REQUESTED** [review]

File: include/nlohmann/detail/macro_scope.hpp (hunk 2 above)
Comment (gregmarr) [reply include/nlohmann/detail/macro_scope.hpp:398]: What change are you expecting to see there?  `NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT` uses `NLOHMANN_JSON_FROM_WITH_DEFAULT`.

Comment (nlohmann) [reply include/nlohmann/detail/macro_scope.hpp:398]: Oh, missed that. Sorry.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by nlohmann** [comment]
Thanks!

File: include/nlohmann/detail/macro_scope.hpp (hunk 2 above)
Comment (NissimBendanan) [reply include/nlohmann/detail/macro_scope.hpp:398]: I don't understand what you are asking

`NLOHMANN_JSON_FROM_WITH_DEFAULT` is called by all the following macros:

- `NLOHMANN_DEFINE_TYPE_INTRUSIVE_WITH_DEFAULT`
- `NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT`
- `NLOHMANN_DEFINE_DERIVED_TYPE_INTRUSIVE_WITH_DEFAULT`
- `NLOHMANN_DEFINE_DERIVED_TYPE_NON_INTRUSIVE_WITH_DEFAULT`

so no matter which external macro is calling, the change will be applied
