### PR TITLE
Fix quadratic destruction complexity

### LINKED ISSUE #1837: Quadratic destruction complexity introduced in #1436
- What is the issue you have?

Recently merged PR #1436 introduced quadratic complexity in destruction of json object due to use of `std::vector::reserve` in a loop. 

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

Benchmark code:
```cpp
#include "benchmark/benchmark.h"
#include "nlohmann/json.hpp"

static void benchmark_json_creation_destruction(benchmark::State &state) {
    size_t N = state.range(0);

    std::string s;
    for (size_t i = 0; i < N; ++i) {
        s += "[1,";
    }
    s += "2";
    for (size_t i = 0; i < N; ++i) {
        s += "]";
    }

    for (auto _ : state) {
        nlohmann::json j;
        j = nlohmann::json::parse(s);
    }
    state.SetComplexityN(N);
}
BENCHMARK(benchmark_json_creation_destruction)
    ->Range(1, 10000)->Complexity(benchmark::oAuto);

int main(int argc, char** argv) {
    benchmark::Initialize(&argc, argv);
    benchmark::RunSpecifiedBenchmarks();
    return 0;
}
```

- What is the expected behavior?

Linear complexity. 

- And what is the actual behavior instead?

Quadratic complexity with 3.7.2:
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
benchmark_json_creation_destruction/1            450 ns          450 ns      1521254
benchmark_json_creation_destruction/8           2283 ns         2282 ns       319664
benchmark_json_creation_destruction/64         19322 ns        19322 ns        33992
benchmark_json_creation_destruction/512       290041 ns       290035 ns         2409
benchmark_json_creation_destruction/4096     9455262 ns      9455230 ns           68
benchmark_json_creation_destruction/10000   53660018 ns     53657883 ns           12
benchmark_json_creation_destruction_BigO        0.54 N^2        0.54 N^2  
benchmark_json_creation_destruction_RMS            2 %             2 %    
```

Same version, with `reserve` calls removed:

```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
benchmark_json_creation_destruction/1            444 ns          444 ns      1376396
benchmark_json_creation_destruction/8           2111 ns         2111 ns       325257
benchmark_json_creation_destruction/64         16713 ns        16713 ns        41177
benchmark_json_creation_destruction/512       118116 ns       118113 ns         5793
benchmark_json_creation_destruction/4096      916147 ns       916078 ns          729
benchmark_json_creation_destruction/10000    2236044 ns      2235964 ns          302
benchmark_json_creation_destruction_BigO      223.63 N        223.62 N    
benchmark_json_creation_destruction_RMS            0 %             0 %    
```

While previous version, 3.7.1, exhibits linear complexity:
```
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
benchmark_json_creation_destruction/1            387 ns          387 ns      1805004
benchmark_json_creation_destruction/8           1578 ns         1578 ns       435509
benchmark_json_creation_destruction/64         10501 ns        10501 ns        65116
benchmark_json_creation_destruction/512       100457 ns       100454 ns         6841
benchmark_json_creation_destruction/4096      764401 ns       764402 ns          871
benchmark_json_creation_destruction/10000    1867051 ns      1867057 ns          371
benchmark_json_creation_destruction_BigO      186.71 N        186.71 N    
benchmark_json_creation_destruction_RMS            0 %             0 %  
```

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Ubuntu 19.10 with GCC 9.2:
```
$ gcc --version
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
```

- Did you use a released version of the library or the version from the `develop` branch?

Release 3.7.2

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

### PR DESCRIPTION
**Pull request by nickaein**
Fixes #1837 along with minor cleanups.

* * *

## Pull request checklist

Read the [Contribution Guidelines](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md) for detailed information.

- [x]  Changes are described in the pull request, or an [existing issue is referenced](https://github.com/nlohmann/json/issues).
- [x]  The test suite [compiles and runs](https://github.com/nlohmann/json/blob/develop/README.md#execute-unit-tests) without error.
- [ ]  [Code coverage](https://coveralls.io/github/nlohmann/json) is 100%. Test cases can be added by editing the [test suite](https://github.com/nlohmann/json/tree/develop/test/src).
- [x]  The source code is amalgamated; that is, after making changes to the sources in the `include/nlohmann` directory, run `make amalgamate` to create the single-header file `single_include/nlohmann/json.hpp`. The whole process is described [here](https://github.com/nlohmann/json/blob/develop/.github/CONTRIBUTING.md#files-to-change).

## Please don't

- The C++11 support varies between different **compilers** and versions. Please note the [list of supported compilers](https://github.com/nlohmann/json/blob/master/README.md#supported-compilers). Some compilers like GCC 4.7 (and earlier), Clang 3.3 (and earlier), or Microsoft Visual Studio 13.0 and earlier are known not to work due to missing or incomplete C++11 support. Please refrain from proposing changes that work around these compiler's limitations with `#ifdef`s or other means.
- Specifically, I am aware of compilation problems with **Microsoft Visual Studio** (there even is an [issue label](https://github.com/nlohmann/json/issues?utf8=✓&q=label%3A%22visual+studio%22+) for these kind of bugs). I understand that even in 2016, complete C++11 support isn't there yet. But please also understand that I do not want to drop features or uglify the code just to make Microsoft's sub-standard compiler happy. The past has shown that there are ways to express the functionality such that the code compiles with the most recent MSVC - unfortunately, this is not the main objective of the project.
- Please refrain from proposing changes that would **break [JSON](http://json.org) conformance**. If you propose a conformant extension of JSON to be supported by the library, please motivate this extension.
- Please do not open pull requests that address **multiple issues**.

### CODE REVIEW

File: include/nlohmann/json.hpp [hunk 1]
```diff
@@ -1004,13 +1004,10 @@ class basic_json
             // move the top-level items to stack
             if (t == value_t::array)
             {
-                stack.reserve(array->size());
```
Comment (gregmarr) [inline include/nlohmann/json.hpp]: This one is actually okay because it's not in a loop.

File: include/nlohmann/json.hpp [hunk 2]
```diff
@@ -1004,13 +1004,10 @@ class basic_json
...
                 std::move(array->begin(), array->end(), std::back_inserter(stack));
             }
             else if (t == value_t::object)
             {
-                stack.reserve(object->size());
```
Comment (gregmarr) [inline include/nlohmann/json.hpp]: This one is actually okay because it's not in a loop.

File: include/nlohmann/json.hpp (hunk 1 above)
Comment (nickaein) [reply include/nlohmann/json.hpp]: Good point! Done.

File: include/nlohmann/json.hpp (hunk 2 above)
Comment (nickaein) [reply include/nlohmann/json.hpp]: Done.

**Comment by nlohmann** [comment]
Thanks everybody!!!

**Comment by nlohmann** [comment]
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Removed `reserve()` calls from the destructor which could lead to quadratic complexity. #1837 #1838

* * *
