### PR TITLE
Properly constrain the basic_json conversion operator

### LINKED ISSUE #2491: Compilation error when using NLOHMANN_JSON_SERIALIZE_ENUM ordered_json on libc++
Usage of `NLOHMANN_JSON_SERIALIZE_ENUM` with `nlohmann::ordered_json` results in a compilation error for libc++ with `-std=c++17` and greater.

#### What is the issue you have?

The `NLOHMANN_JSON_SERIALIZE_ENUM` expands to the custom `to_json` and `from_json` functions. Both of these functions have the following code:
```cpp
static const std::pair<Enum, BasicJsonType> m[] = /* macro argument */;
```

And they work fine with using GCC or using (Clang + libstdc++) or using (Clang + libc++) but trying to convert enum value to `nlohmann::json`, but when (Clang + libc++) is used and enum value is converting to `nlohmann::ordered_json` then there is a compilation error.
<details><summary>Entire compiler output with error</summary>

```
In file included from <source>:1:
In file included from /opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:37:
In file included from /opt/compiler-explorer/clang-11.0.0/bin/../include/c++/v1/algorithm:642:
/opt/compiler-explorer/clang-11.0.0/bin/../include/c++/v1/utility:514:58: error: no member named 'value' in 'std::__1::is_copy_assignable<nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>'
                        is_copy_assignable<second_type>::value,
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:3856:17: note: in instantiation of template class 'std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>' requested here
    -> decltype(from_json(j, val), void())
                ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:4451:17: note: while substituting deduced template arguments into function template 'operator()' [with BasicJsonType = nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, T = nlohmann::ordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, std::__1::less<void>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>>> *]
    -> decltype(::nlohmann::from_json(std::forward<BasicJsonType>(j), val), void())
                ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:3094:37: note: while substituting deduced template arguments into function template 'from_json' [with BasicJsonType = const nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>> &, ValueType = nlohmann::ordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, std::__1::less<void>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>>> *]
using from_json_function = decltype(T::from_json(std::declval<Args>()...));
                                    ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:2911:33: note: in instantiation of template type alias 'from_json_function' requested here
struct detector<Default, void_t<Op<Args...>>, Op, Args...>
                                ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:2921:1: note: during template argument deduction for class template partial specialization 'detector<Default, void_t<Op<Args...>>, Op, Args...>' [with Default = nlohmann::detail::nonesuch, Op = from_json_function, Args = <nlohmann::adl_serializer<nlohmann::ordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, std::__1::less<void>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>>> *, void>, const nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>> &, nlohmann::ordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, std::__1::less<void>, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>>> *&>]
using detected_t = typename detector<nonesuch, void, Op, Args...>::type;
^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:2921:1: note: (skipping 22 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
<source>:12:50: note: in instantiation of template class 'std::__1::pair<Enum1, nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>' requested here
    static const std::pair<Enum1, BasicJsonType> m[] = { 
                                                 ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:4420:16: note: in instantiation of function template specialization 'to_json<nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>>' requested here
        return to_json(j, std::forward<T>(val));
               ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:4470:9: note: in instantiation of function template specialization 'nlohmann::detail::to_json_fn::operator()<nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, Enum1>' requested here
        ::nlohmann::to_json(j, std::forward<ValueType>(val));
        ^
/opt/compiler-explorer/libs/nlohmann_json/trunk/single_include/nlohmann/json.hpp:18014:28: note: in instantiation of function template specialization 'nlohmann::adl_serializer<Enum1, void>::to_json<nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>, Enum1>' requested here
        JSONSerializer<U>::to_json(*this, std::forward<CompatibleType>(val));
                           ^
<source>:19:32: note: in instantiation of function template specialization 'nlohmann::basic_json<nlohmann::ordered_map, std::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long, unsigned long, double, std::allocator, adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>::basic_json<Enum1, Enum1, 0>' requested here
    nlohmann::ordered_json j = Enum1::Value1;
                               ^
```

</details>

This probably depends on C++ standard version in libc++, for example with `-std=c++11` and `-std=c++14` it works fine.

#### Please describe the steps to reproduce the issue.

You can reproduce the issue by looking at this useful example on [Compiler Explorer](https://godbolt.org/z/Tfjc96) with Clang 11.0.0 and `-std=c++17`.
Note that `NLOHMANN_JSON_SERIALIZE_ENUM` is expanded already there and a bit simplified, if this is not necessary then here is also an [example](https://godbolt.org/z/9Gehe5) without `NLOHMANN_JSON_SERIALIZE_ENUM` macro expansion.

[Example](https://godbolt.org/z/a7fY89) with only `std::is_copy_assignable<nlohmann::ordered_json>::value` usage that also fails.

Clang 11.0.0 with `-std=c++14` compiles this code on [Compiler Explorer](https://godbolt.org/z/bbf636).

#### Can you provide a small but working code example?

```cpp
#include "nlohmann/json.hpp"

enum class Enum1
{
    Value1,
    Value2
};

NLOHMANN_JSON_SERIALIZE_ENUM( Enum1,
{
    {Enum1::Value1,   "Enum1::Value1"},
    {Enum1::Value2,   "Enum1::Value2"},
})

int main()
{
    nlohmann::ordered_json j = Enum1::Value1;
}
```

#### What is the expected behavior?

It should compile

#### And what is the actual behavior instead?

Compilation error

#### Which compiler and operating system are you using?

- Compiler: Clang 11 + libc++-11 on PC, Clang on Compiler Explorer
- Operating system: Ubuntu 20.10

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [x] "trunk" on Compiler Explorer

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [x] yes

### PR DESCRIPTION
**Pull request by ldionne**
Fixes #2491

This was reported as a libc++ bug in http://llvm.org/PR48507, but it's a bug in this library, not in libc++. See Richard Smith's explanation in http://llvm.org/PR48507.

### CODE REVIEW

**Comment by ldionne** [comment]
I'm not sure what standards you support. If some of the type traits (e.g. `std::conjunction`) are not available on all the compilers you support, it's easy to fix that by implementing our own. Just let me know.

I'm now going to close http://llvm.org/PR48507 because it's not a libc++ bug.

File: include/nlohmann/detail/meta/detected.hpp [hunk 1]
```diff
@@ -39,6 +39,9 @@ struct detector<Default, void_t<Op<Args...>>, Op, Args...>
 template<template<class...> class Op, class... Args>
 using is_detected = typename detector<nonesuch, void, Op, Args...>::value_t;
 
+template<template<class...> class Op, class... Args>
+struct is_detected_lazy : is_detected<Op, Args...> { };
```
Comment (alexezeder) [inline include/nlohmann/detail/meta/detected.hpp:43]: IMHO, That's done way better than in my PR. I like the idea of making the number of additional instantiations as small as possible, and this allows to eliminate unnecessary instantiations. 👍

File: include/nlohmann/json.hpp [hunk 2]
```diff
@@ -3342,16 +3342,18 @@ class basic_json // NOLINT(cppcoreguidelines-special-member-functions,hicpp-spec
...
+                        std::negation<std::is_same<ValueType, std::initializer_list<typename string_t::value_type>>>,
+
 #if defined(JSON_HAS_CPP_17) && (defined(__GNUC__) || (defined(_MSC_VER) && _MSC_VER >= 1910 && _MSC_VER <= 1914))
-                   && !std::is_same<ValueType, typename std::string_view>::value
+                        std::negation<std::is_same<ValueType, std::string_view>>,
 #endif
-                   && detail::is_detected<detail::get_template_function, const basic_json_t&, ValueType>::value
-                   , int >::type = 0 >
+                        detail::is_detected_lazy<detail::get_template_function, const basic_json_t&, ValueType>
+                    >::value, int >::type = 0 >
```
Comment (alexezeder) [inline include/nlohmann/json.hpp:3356]: IMHO, there is no much sense to use templated/typed/parametrized logic operations for all operands. For the same reason as above. Of course, it can backfire in the future, but it wouldn't hurt too much since these operands can be replaced pretty quickly.

**Review by alexezeder — COMMENTED** [review]
Just two comments to compare with my PR. The appearance of a new PR made me update mine. 😉

File: include/nlohmann/json.hpp (hunk 2 above)
Comment (ldionne) [reply include/nlohmann/json.hpp:3356]: You could technically do something like:

```c++
std::conjunction<
    std::bool_constant<
        !std::is_pointer<ValueType>::value &&
        !std::is_same<ValueType, detail::json_ref<basic_json>>::value &&
        !std::is_same<ValueType, typename string_t::value_type>::value &&
        !detail::is_basic_json<ValueType>::value &&
        !std::is_same<ValueType, std::initializer_list<typename string_t::value_type>>::value &&
        // ...
    >,
    detail::is_detected_lazy<detail::get_template_function, const basic_json_t&, ValueType>
>
```

But I don't think it provides a big benefit, and it's less consistent.

File: include/nlohmann/detail/meta/detected.hpp (hunk 1 above)
Comment (ldionne) [reply include/nlohmann/detail/meta/detected.hpp:43]: > Just two comments to compare with my PR. The appearance of a new PR made me update mine. 😉

Sorry, I didn't realize there was already a PR for this.

File: include/nlohmann/json.hpp (hunk 2 above)
Comment (alexezeder) [reply include/nlohmann/json.hpp]: Yeah, actually, it's
https://github.com/nlohmann/json/blob/ae9cfb17bd960ae014b01ac62ecf22d72cde4ee5/include/nlohmann/json.hpp#L3345-L3357

You are right about consistency for sure. Does it give a big benefit - I don't know, I'm just hoping that it helps. But looking more at this library, probably a few more instantiations wouldn't be noticeable.

File: test/src/unit-bug2491.cpp [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+OUT OF OR IN CONNECTION WITH THE SOFTWARE  OR THE USE OR OTHER DEALINGS IN THE
+SOFTWARE.
+*/
+
+#include "doctest_compatibility.h"
+
+#include <nlohmann/json.hpp>
+#include <type_traits>
+
+static_assert(std::is_copy_assignable<nlohmann::ordered_json>::value, "");
```
Comment (nlohmann) [inline test/src/unit-bug2491.cpp:35]: Can you please move this to `test/src/unit-regression2.cpp`?

File: include/nlohmann/detail/meta/type_traits.hpp [hunk 4]
```diff
@@ -157,6 +157,9 @@ template<class B1, class... Bn>
 struct conjunction<B1, Bn...>
 : std::conditional<bool(B1::value), conjunction<Bn...>, B1>::type {};
 
+// https://en.cppreference.com/w/cpp/types/negation
+template<class B> struct negation : std::integral_constant<bool, !B::value> { };
```
Comment (nlohmann) [inline include/nlohmann/detail/meta/type_traits.hpp:161]: Wouldn't this be rather `negation_v`?

**Review by nlohmann — CHANGES_REQUESTED** [review]
Can you please update this branch to the latest develop branch?

File: include/nlohmann/detail/meta/type_traits.hpp (hunk 4 above)
Comment (gregmarr) [reply include/nlohmann/detail/meta/type_traits.hpp:161]: `negation` is the base struct, `negation_v` is 

    template<class B>
    inline constexpr bool negation_v = negation<B>::value;

Comment (nlohmann) [reply include/nlohmann/detail/meta/type_traits.hpp:161]: Ah - I read the `::value` at the wrong place. Thanks!

**Comment by ldionne** [comment]
Rebased onto `develop` and renamed test as requested.

File: test/src/unit-regression3.cpp [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+OUT OF OR IN CONNECTION WITH THE SOFTWARE  OR THE USE OR OTHER DEALINGS IN THE
+SOFTWARE.
+*/
+
+#include "doctest_compatibility.h"
+
+#include <nlohmann/json.hpp>
+#include <type_traits>
+
+static_assert(std::is_copy_assignable<nlohmann::ordered_json>::value, "");
```
Comment (nlohmann) [inline test/src/unit-regression3.cpp:35]: No, I meant moving this test into `test/src/unit-regression2.cpp` - best create a new `SECTION` at the end of this file and move the `static_assert` in there.

**Review by nlohmann — CHANGES_REQUESTED** [review]

**Review by nlohmann — CHANGES_REQUESTED** [review]
The test for the amalgamation (https://github.com/nlohmann/json/runs/3104916288?check_suite_focus=true) failed. Can you please run `make amalgamate` - this should re-indent and regenerate the single header.

**Comment by ldionne** [comment]
> The test for the amalgamation (https://github.com/nlohmann/json/runs/3104916288?check_suite_focus=true) failed. Can you please run `make amalgamate` - this should re-indent and regenerate the single header.

It looks like there's nothing to be done on my system for `amalgamate`:

```
% make amalgamate
make: Nothing to be done for `amalgamate'.
```

**Comment by nlohmann** [comment]
> It looks like there's nothing to be done on my system for `amalgamate`:
> 
> ```
> % make amalgamate
> make: Nothing to be done for `amalgamate'.
> ```

That is strange. Can you try to delete file `single_include/nlohmann/json.hpp` and re-run `make amalgamate`?

**Comment by ldionne** [comment]
> > It looks like there's nothing to be done on my system for `amalgamate`:
> > ```
> > % make amalgamate
> > make: Nothing to be done for `amalgamate'.
> > ```
> 
> That is strange. Can you try to delete file `single_include/nlohmann/json.hpp` and re-run `make amalgamate`?

Now that seems to make a difference, thanks.

**Comment by nlohmann** [comment]
The remaining issue in the CI has been fixed in the develop branch, so technically this PR is ready to be merged.

As I am no expert in template magic, I do no really understand the fix. @gregmarr @alexezeder can either of you have a quick look whether the changes are OK to you?

**Comment by alexezeder** [comment]
> @alexezeder can either of you have a quick look whether the changes are OK to you?

I cannot call myself an expert in template magic either, but since I understand what causes the errors here - the changes are OK to me. I've already reviewed this PR, and I agree with the @ldionne that it's not worth changing logic operations for all operands for consistency. Also, as @ldionne mentioned, it doesn't provide a big benefit.

**Review by nlohmann — APPROVED** [review]
Looks good to me.

**Comment by nlohmann** [comment]
Thanks!
